### PR TITLE
[ADAM-1359] Merge `reads2fragments` and `fragments2reads` into `transformFragments`

### LINKED ISSUE #1359: Merge reads2fragments and fragments2reads into a single CLI
Splitting this out of #1309.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1359. Also, propegates the quality score binner (#1485) up to the
`transformFragments` CLI.

### CODE REVIEW

**Comment by heuermh** [comment]
Looks like we need to kill the current Jenkins job and try again.  Will retest this please do the trick?

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
@heuermh there were some issues with Jenkins this weekend, so I'm guessing the build got killed during a Jenkins restart.

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Pull request merged**
