### PR TITLE
[ADAM-1853] Various improvements to readthedocs documentation.

### LINKED ISSUE #1853: Various improvements to readthedocs documentation
Suggestions for various improvements to readthedocs documentation:
- [ ] Source code css style could be better (clearer difference between comments and code, no bold text)
- [ ] CSS layout doesn't expand horizontally for wide browser windows
- [ ] Can't read pipe method source without horizontal scrolling (this holds true for almost all code blocks)
- [ ] `http://adam.readthedocs.io/en/latest/_images/grdd.png` is unreadable at normal size
- [x] `./bin/adam-submit flagstat NA12878_chr20.adam` could drop the `./bin/` to match other examples
- [ ] Java example on pipe API doc page doesn't read the same as other languages, doesn't have loadXxx
- [ ] There is no reference for the formats schema, java classes, and product scala classes (although perhaps the latter will show up in the latest scaladoc?)
- [x] Figures on `http://adam.readthedocs.io/en/latest/benchmarks/algorithms/` should use GATK4 as a label
- [x] Is it "GATK" or "the GATK"?
- [x] GATK in "...more performant than the same algorithms implemented in the GATK. ADAM outperforms the GATK when running..." should be GATK4
- [x] GATK4 comparison is missing in INDEL Realignment figure
- [x] Remove CGCloud section from deploying doc
- [x] Note that Conductor is not appropriate for uploading Parquet directories to S3 in `http://adam.readthedocs.io/en/latest/deploying/cgcloud/#bulk-transfer-between-hdfs-and-s3`, suggest s3a via AWS CLI or s3-dist-cp
- [ ] Add deploying on EMR doc with example config
- [x] Drop `./bin/` in examples on `http://adam.readthedocs.io/en/latest/deploying/yarn/`
- [x] Bold fixed-width font in `An example workflow: toil_scripts.adam_kmers.count_kmers` is kind of obnoxious
- [x] Strange layout on `http://adam.readthedocs.io/en/latest/api/adamContext/`, note blank lines between "loadIndexedBam" and "(Scala only)"
- [x] Incorrect link anchor in `RDDs are processed by running functional [transformations]{#transforming} across the whole dataset.`
- [x] Split `http://adam.readthedocs.io/en/latest/_images/join_examples.png` into two figures
- [x] Nested bullets didn't work at `AlignmentRecordRDD: InFormatters: SAMInFormatter and BAMInFormatter write SAM or BAM out to a pipe.`
- [ ] Mention Cannoli in `http://adam.readthedocs.io/en/latest/api/pipes/`
- [x] Links on `http://adam.readthedocs.io/en/latest/downstream/overview/` do not work
- [x] Links on `http://adam.readthedocs.io/en/latest/downstream/cli` are not correct, e.g. `http://adam.readthedocs.io/en/latest/downstream/cli/#build-new-command` should be `http://adam.readthedocs.io/en/latest/downstream/cli/#extend-the-adam-cli-by-adding-new-commands-in-an-external-repository`
- [ ] Should https://github.com/heuermh/adam-examples and https://github.com/heuermh/adam-commands be migrated to bigdatagenomics organization?
- [x] Left margin in BQSR `read ←the read to observe` block looks incorrect
- [x] Inline math formatting in RI `reads mathbf{r}, we`, ` l_s denotes` and `q_c value` look incorrect
- [x] Should `http://adam.readthedocs.io/en/latest/#introduction` section be its own page, separate from the Table of Contents?
- [x] Should `http://adam.readthedocs.io/en/latest/#references` section be its own page?
- [x] Add `https://github.com/bigdatagenomics/adam#citing-adam` section or as new page
- [ ] Index `http://adam.readthedocs.io/en/latest/genindex/` is empty
- [x] Confirm http://adam.readthedocs.io/en/latest is actually the latest (git head)
- [x] Similar blank line problem with bullets on Table of Contents page, between BWA, and bowtie2, FreeBayes)
- [x] http://adam.readthedocs.io/en/latest/deploying/aws/ is missing from Table of Contents
- [x] RI inline doc refers to `s(i)` but I don't see it in the equation

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1853.

### CODE REVIEW

**Comment by heuermh** [comment]
Updated checkboxes at #1853 to show what this pull request addresses.

**Comment by fnothaft** [comment]
Nice! Are you still working on the issues left in #1853, or is this as far as you're getting?

**Comment by heuermh** [comment]
> Are you still working on the issues left in #1853, or is this as far as you're getting?

Let's see ... these ones need help/feedback from you

- [ ] RI inline doc refers to `s(i)` but I don't see it in the equation
- [ ] Left margin in BQSR `read ←the read to observe` block looks incorrect
- [ ] Figures on `http://adam.readthedocs.io/en/latest/benchmarks/algorithms/` should use GATK4 as a label
- [ ] Is it "GATK" or "the GATK"?
- [ ] GATK in "...more performant than the same algorithms implemented in the GATK. ADAM outperforms the GATK when running..." should be GATK4
- [ ] GATK4 comparison is missing in INDEL Realignment figure

I tried messing around with the CSS but couldn't find a easy way to make code blocks wider without completely overhauling the layout (everything uses static widths).

This one I'll add soon in a separate PR along with new pages for homebrew, conda, and docker

- [ ] Add deploying on EMR doc with example config

**Comment by fnothaft** [comment]
> GATK4 comparison is missing in INDEL Realignment figure

GATK4 drops the INDEL realigner.

Otherwise, I'll PR the others over to you shortly.

**Comment by fnothaft** [comment]
RE: Is it "GATK" or "the GATK"?

We're consistently using `the GATK`:

```
$ cd docs
$ grep GATK -R . | grep -v "the GATK"
./algorithms/reads.rst:   implementation is fully concordant with the Picard/GATK duplicate
```

**Comment by fnothaft** [comment]
@heuermh I think all of the ones that needed action from me will be resolved after you merge https://github.com/heuermh/adam/pull/6.

**Pull request merged**
