### PR TITLE
more permissible jar regex in adam-submit

### LINKED ISSUE #974: Allow lowercase letters in jar/version names
I sometimes build ADAM assembly JARs with the abbreviated git sha as the maven version; currently `adam-{shell,submit}` check for JARs with only numbers and uppercase letters, so they miss these.

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #974

### CODE REVIEW

**Comment by heuermh** [comment]
LGTM

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by fnothaft** [comment]
LGTM!

**Comment by heuermh** [comment]
Merged via 34f6dc21d551382b2ea135ff19703196b6a2cd1d

Thank you, @ryan-williams!

**Pull request closed without merging**
