### PR TITLE
P Operator parsing for MDTag

### PR DESCRIPTION
**Pull request by arahuja**

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM! OOC, how are you getting a `P` in the middle of a CIGAR? (Or, was that just a unit test case?)

**Comment by heuermh** [comment]
We should be able to get a version 0.18.2 release out shortly with this in it, if that helps.

**Comment by arahuja** [comment]
@fnothaft @heuermh Yes, it was just a unit test that had this issue for us - is a P unexpected in the middle of a CIGAR?  I did a quick look through a handful of BAMs I had honestly did not find any P's and have run other ADAM utilities without this cropping up, so I'm not sure I've ever seen a CIGAR `P` in real data.

**Comment by fnothaft** [comment]
OK! Cool. I was just curious. Let me merge this now...

**Comment by fnothaft** [comment]
Thanks @arahuja!

**Pull request merged**
