### PR TITLE
Resolve #1508, #1509 for Pipe API

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1508, #1509. WIP, still being tested.

### CODE REVIEW

**Comment by fnothaft** [comment]
@heuermh can do! I'll be testing this later today, and will add the unit test as well.

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
@heuermh Rebased and added the test.

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Pull request merged**
