### PR TITLE
[ADAM-937] Adding check for aligned read predicate or limit projection flags and non-parquet input path

### LINKED ISSUE #937: Transform -limit_projection requires .sam.seqdict file
ADAM transform of SAM or BAM formatted files with ```-limit_projection``` option throws difficult to interpret error message about missing ```.{sam,bam}.seqdict``` file.

```bash
$ ./bin/adam-submit transform adam-core/src/test/resources/small.sam -limit_projection small-limit.adam
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-submit
2016-02-10 13:20:25 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Command body threw exception:
java.io.FileNotFoundException: File adam-core/src/test/resources/small.sam.seqdict does not exist
Exception in thread "main" java.io.FileNotFoundException: File adam-core/src/test/resources/small.sam.seqdict does not exist
	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:534)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:747)
	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:524)
	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:409)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSInputChecker.<init>(ChecksumFileSystem.java:140)
	at org.apache.hadoop.fs.ChecksumFileSystem.open(ChecksumFileSystem.java:341)
	at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:766)
	at org.bdgenomics.adam.rdd.ADAMContext.loadAvro(ADAMContext.scala:401)
	at org.bdgenomics.adam.rdd.ADAMContext.loadParquetAlignments(ADAMContext.scala:477)
	at org.bdgenomics.adam.cli.Transform.run(Transform.scala:264)
	at org.bdgenomics.utils.cli.BDGSparkCommand$class.run(BDGCommand.scala:54)
	at org.bdgenomics.adam.cli.Transform.run(Transform.scala:119)
	at org.bdgenomics.adam.cli.ADAMMain.apply(ADAMMain.scala:136)
	at org.bdgenomics.adam.cli.ADAMMain$.main(ADAMMain.scala:76)
	at org.bdgenomics.adam.cli.ADAMMain.main(ADAMMain.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #937

### CODE REVIEW

**Comment by heuermh** [comment]
I'm not sure this is comprehensive enough, e.g. sometimes even Parquet files won't have ```.seqdict``` files
```bash
$ ./bin/adam-submit fasta2adam \
  adam-cli/src/test/resources/contigs.fa contigs.contig.adam

$ ./bin/adam-submit transform -aligned_read_predicate \
  contigs.contig.adam output.adam

Command body threw exception:
java.io.FileNotFoundException: File contigs.contig.adam.seqdict does not exist
  Exception in thread "main" java.io.FileNotFoundException:
    File contigs.contig.adam.seqdict does not exist
```

**Comment by fnothaft** [comment]
Sorry; should be checking that the file is a Parquet file of alignment records.

Alternatively, we could make this a `ValidationStringency` effect. E.g., if you have `ValidationStringency.LENIENT`, we give a `RecordGroupDictionary.empty`/`SequenceDictionary.empty` if they're missing.

**Comment by heuermh** [comment]
> Sorry; should be checking that the file is a Parquet file of alignment records.

What do you mean by this, flipping the logic of ```isNonParquet``` around?

**Comment by fnothaft** [comment]
> What do you mean by this, flipping the logic of isNonParquet around?

Oh, I just meant that it shouldn't check for _any_ Parquet dataset. Rather, the check should be more specific and check that it is a Parquet dataset of `AlignmentRecord`s.

**Comment by heuermh** [comment]
Can't do that by filename check, so it would have to come later, instead of fail fast in the cli class.

**Comment by fnothaft** [comment]
Ah, yes, fair. I think we suggest "*.contig.adam" as a convention for files of `NucleotideContigFragment`s, but we don't enforce it anywhere. We can patch that later, if needed.

Do you want to do any of the `ValidationStringency` stuff I suggested earlier, or shall we skip that for now and possibly come back to it later?

**Comment by heuermh** [comment]
> I think we suggest "*.contig.adam" as a convention for files of NucleotideContigFragments, but we don't enforce it anywhere.

Yep, I cribbed from here
https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ADAMContext.scala#L858

I can add the check for ```*.contig.adam``` if useful.  I think validation strategy might be overkill.

**Comment by fnothaft** [comment]
> I can add the check for *.contig.adam if useful. I think validation strategy might be overkill.

This is probably sufficient for now. We can add the two later if need be. I'll merge this shortly.

**Comment by massie** [comment]
Thanks, Michael.

**Comment by massie** [comment]
Merged manually.

**Pull request closed without merging**
