### PR TITLE
[ADAM-1573] Remove unused Unaligned trait.

### LINKED ISSUE #1573: Unaligned Trait does nothing
It seems like the `Unaligned` trait isn't doing [anything](https://github.com/bigdatagenomics/adam/blob/c78a0edfde4a06beed6dbe74808c135744fd3c71/adam-core/src/main/scala/org/bdgenomics/adam/rdd/GenomicRDD.scala#L1419). Should it be removed?

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1573.

### CODE REVIEW

**Comment by fnothaft** [comment]
@shaneknapp it looks like our build is getting SIGKILLed on @AmplabJenkins. Thoughts?

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Comment by shaneknapp** [comment]
hrm.  things seem fine now, but lemme take a look at the logs.

shane (who can't wait to get rid of these boxes)

**Comment by shaneknapp** [comment]
wow.  i literally have no idea what happened.  the builds that were SIGKILLED were spread over a few different workers, there's nothing in any of the system or jenkins logs and dmesg looks fine.

and now things are building fine.

nothing to see here, please move along!  everything is fine!
fine

**Pull request merged**
