### PR TITLE
[ADAM-640] Fix incorrect exclusion for org.seqdoop.htsjdk.

### LINKED ISSUE #640: org.seqdoop.htsjdk is incorrectly excluded
#619 incorrectly excludes `com.seqdoop.htsjdk` instead of `org.seqdoop.htsjdk`.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #640.

### CODE REVIEW

**Comment by fnothaft** [comment]
If we can merge this quickly, that'd be good as it is needed for https://github.com/bigdatagenomics/avocado/pull/127.

**Comment by massie** [comment]
Will do.


-Matt

**Comment by fnothaft** [comment]
Thanks!

**Comment by massie** [comment]
Thanks, Frank!

**Pull request merged**
