### PR TITLE
Rename org.bdgenomics.adam.rdd.features package to o.b.a.rdd.feature

### PR DESCRIPTION
**Pull request by heuermh**
See https://github.com/bigdatagenomics/adam/issues/1083#issuecomment-233494794

### CODE REVIEW

**Comment by fnothaft** [comment]
Oh, that's just dandy. #1254 spuriously passed tests because the artifact renaming broke but there were no binary changes so pulling from Maven Central caused downstream modules to build OK. That's why the Spark 2 builds are failing here.

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!

**Pull request merged**
