### PR TITLE
Add loadReadsFromSamString function into ADAMContext		

### PR DESCRIPTION
**Pull request by xubo245**
add loadReadsFromSamString function into ADAMContext,
add some annotation for loadReadsFromSamString

link: https://github.com/bigdatagenomics/adam/issues/1425

I have finished it in adam-0.19.0 and update for Adam-0.21.1-SNAPSHOT today.

@fnothaft @heuermh 

The first and second commits is not related about link: https://github.com/bigdatagenomics/adam/issues/1425. But I do not known how to remove it, sorry.
The two commits has been PR: https://github.com/bigdatagenomics/adam/pull/1433

### CODE REVIEW

**Comment by xubo245** [comment]
I can not understand the FAILed information...It is different from mine.

Where error in my code?

**Comment by fnothaft** [comment]
Hi @xubo245! Similar to my comment on [your other PR](https://github.com/bigdatagenomics/adam/pull/1433#issuecomment-286334186), this is just our source formatting check failing; you can fix this by running `./scripts/format-source`. Let me know if you have any problems running that. Thank you again for the contribution, and I hope to make a review pass tomorrow!

**Comment by xubo245** [comment]
I just run ./scripts/format-source and PR in this issue.

Is it OK?

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by xubo245** [comment]
The conflicts need be resolved by me？

**Comment by xubo245** [comment]
Is it correct that the conflicts  be resolved?

**Comment by xubo245** [comment]
Cloud it be merge?

It is second time that show conflicts  with ADAMContext.scala

**Comment by heuermh** [comment]
@xubo245 sorry about the conflicts, we'll review and help rebase/squash commits after the 0.22.0 release is cut tomorrow.

**Comment by xubo245** [comment]
@heuermh  Clould you help me to deal with this commits ?

**Comment by xubo245** [comment]
This PR has more than a month...

**Comment by xubo245** [comment]
Cloud you help me to deal with this commits ? @fnothaft @heuermh

**Comment by heuermh** [comment]
@xubo245 I took a closer look at this last week.  Even with the commits straightened out, I feel like I'm missing the use case.  What would this provide that say the Pipe API does not?

**Comment by xubo245** [comment]
the use case: When we invoke read mapping tools in spark, read mapping return RDD(sam format), It need to transform Adam. If write to local Filesystem, it waste time...
It has been described in https://github.com/bigdatagenomics/adam/issues/1425

**Comment by fnothaft** [comment]
Closing in favor of sending users to the [pipe API](http://adam.readthedocs.io/en/adam-parent_2.11-0.23.0/api/pipes/).

**Comment by xubo245** [comment]
@fnothaft  You require me raise this PR before, but now don't merge...

**Pull request closed without merging**
