### PR TITLE
[ADAM-1688] Remove dependency on org.hammerlab:genomic-loci.

### LINKED ISSUE #1688: Conflict in bdg-formats dependency version due to org.hammerlab:genomic-loci
```
$ mvn dependency:tree
...
[INFO] +- org.hammerlab:genomic-loci_2.10:jar:1.4.4:compile
[INFO] |  +- org.hammerlab:args4s_2.10:jar:1.0.0:compile
[INFO] |  +- org.bdgenomics.bdg-formats:bdg-formats:jar:0.10.0:compile
[INFO] |  +- org.hammerlab:iterator_2.10:jar:1.0.0:compile
[INFO] |  |  \- org.spire-math:spire_2.10:jar:0.11.0:compile
[INFO] |  |     +- org.spire-math:spire-macros_2.10:jar:0.11.0:compile
[INFO] |  |     +- org.typelevel:machinist_2.10:jar:0.4.1:compile
[INFO] |  |     \- org.scalamacros:quasiquotes_2.10:jar:2.0.1:compile
[INFO] |  \- org.hammerlab:string-utils_2.10:jar:1.0.0:compile
```

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1688, alternative to #1690.

### CODE REVIEW

**Comment by fnothaft** [comment]
I have a preference for #1690. Why do you prefer this?

**Comment by heuermh** [comment]
> Why do you prefer this?

I'd rather have these +24 lines of code than have to deal with dependency problems.

**Comment by fnothaft** [comment]
The dependency you're worried about is bdg-formats, right? From a grep of the source, I don't think genomic-loci actually use bdg-formats, so an exclusion should be sufficient.

**Comment by heuermh** [comment]
No, I'm worried about org.hammerlab generally.  I was hesitant to bring it in initially, and after further consideration, I would rather not have the dependency.

**Comment by fnothaft** [comment]
BTW, have you identified any issues in genomic-loco WRT GRCh38/HLA contig names? If so, let's patch the issue upstream, no?

**Comment by fnothaft** [comment]
Closing; resolved by #1690.

**Pull request closed without merging**
