### PR TITLE
[ADAM-1822] Misc docs cleanup

### PR DESCRIPTION
**Pull request by fnothaft**
WIP

### CODE REVIEW

**Comment by heuermh** [comment]
Do you know how to fix this one?
```
\#errors(cov)+1
\#observations(cov)+2
```

**Comment by heuermh** [comment]
Created pull request https://github.com/fnothaft/adam/pull/23 against your branch.

**Comment by fnothaft** [comment]
Thanks for the ping on those last two @heuermh; I've pushed two commits that address them. Is this ready to merge from your end?

**Comment by heuermh** [comment]
Yes, LGTM.  Let me know if the commits are how you'd like them.  I'll merge later this morning.

**Comment by heuermh** [comment]
Fixes #1822

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
