### PR TITLE
[ADAM-777] Add validation stringency flag for BQSR.

### LINKED ISSUE #777: MD Tag parsing errors during creation of DecadentRead in BQSR
Reported by @beaunorgeot via email. Exception, with relevant stack trace is:

```
java.lang.IllegalArgumentException: Error "(D,Some(3)) (of class scala.Tuple2)" while constructing DecadentRead from Read({"contig": {"contigName": "1", "contigLength": 249250621, "contigMD5": "1b22b98cdeb4a9304cb5d48026a85128", "referenceURL": "http:\/\/www.broadinstitute.org\/ftp\/pub\/seq\/references\/Homo_sapiens_assembly19.fasta", "assembly": "GRCh37", "species": "Homo Sapiens"}, "start": 248262648, "oldPosition": null, "end": 248262721, "mapq": 23, "readName": "C0FPVACXX120305:4:1303:12410:97560", "sequence": "GATCTTTTCAACAGTTACAGCAGAAAGTTTTCATGGAGAAATGGAATCACACTTCAAATGATTTCATTTTGTTGGG", "qual": "IBBHEFFEKFCKFHFACKFIJFJDCFHFEEDJBCHIFIDDBCGJDBBJAJBJFCIDCACHBDEBHADDDADDAED;", "cigar": "4S1M1D71M", "oldCigar": null, "basesTrimmedFromStart": 0, "basesTrimmedFromEnd": 0, "readPaired": true, "properPair": true, "readMapped": true, "mateMapped": true, "firstOfPair": false, "secondOfPair": true, "failedVendorQualityChecks": false, "duplicateRead": false, "readNegativeStrand": true, "mateNegativeStrand": false, "primaryAlignment": true, "secondaryAlignment": false, "supplementaryAlignment": false, "mismatchingPositions": "3^C71", "origQual": "JJJJIJJJJJJJJJIJJJJJJJJJJJJJJJJJJIJJJJJJJIJJJJIHFHHJJJJJJJJJJJJHHHHHFFFFFCCC", "attributes": "UQ:i:0\tOQ:Z:JJJJIJJJJJJJJJIJJJJJJJJJJJJJJJJJJIJJJJJJJIJJJJIHFHHJJJJJJJJJJJJHHHHHFFFFFCCC\tMQ:i:25\tSM:i:23\tNM:i:1\tAM:i:23\tRG:Z:C0FPV.4\tPG:Z:bwa.6\tTLEN:i:-70", "recordGroupName": "C0FPV.4", "recordGroupSequencingCenter": "BI", "recordGroupDescription": null, "recordGroupRunDateEpoch": 1330923600000, "recordGroupFlowOrder": null, "recordGroupKeySequence": null, "recordGroupLibrary": "Pond-140867", "recordGroupPredictedMedianInsertSize": null, "recordGroupPlatform": "illumina", "recordGroupPlatformUnit": "C0FPVACXX120305.4.TGTAACTC", "recordGroupSample": "JJN-3", "mateAlignmentStart": 248262650, "mateAlignmentEnd": null, "mateContig": {"contigName": "1", "contigLength": 249250621, "contigMD5": "1b22b98cdeb4a9304cb5d48026a85128", "referenceURL": "http:\/\/www.broadinstitute.org\/ftp\/pub\/seq\/references\/Homo_sapiens_assembly19.fasta", "assembly": "GRCh37", "species": "Homo Sapiens"}})
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:40)
	at org.bdgenomics.adam.rich.DecadentRead$.apply(DecadentRead.scala:32)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at org.bdgenomics.adam.rich.DecadentRead$$anonfun$cloy$1.apply(DecadentRead.scala:50)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
	at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$23.apply(RDD.scala:918)
	at org.apache.spark.rdd.RDD$$anonfun$23.apply(RDD.scala:918)
	at org.apache.spark.SparkContext$$anonfun$30.apply(SparkContext.scala:1389)
	at org.apache.spark.SparkContext$$anonfun$30.apply(SparkContext.scala:1389)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: scala.MatchError: (D,Some(3)) (of class scala.Tuple2)
	at org.bdgenomics.adam.util.MdTag$.apply(MdTag.scala:70)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag$lzycompute(RichAlignmentRecord.scala:98)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.mdTag(RichAlignmentRecord.scala:96)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceBase$1(RichAlignmentRecord.scala:180)
	at org.bdgenomics.adam.rich.RichAlignmentRecord.getReferenceContext(RichAlignmentRecord.scala:196)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:217)
	at org.bdgenomics.adam.rich.RichAlignmentRecord$$anonfun$1$$anonfun$2.apply(RichAlignmentRecord.scala:215)

```

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #777.

### CODE REVIEW

**Comment by heuermh** [comment]
The code looks reasonable to me.  Could you add the the failing read (or a similar one) as a test case to demonstrate the fix?

**Comment by fnothaft** [comment]
@beaunorgeot can you test with this patch to see if this passes on your end?

**Comment by fnothaft** [comment]
@heuermh I am working on unit tests.

**Comment by heuermh** [comment]
+1

**Comment by beaunorgeot** [comment]
@fnothaft this patched worked successfully for me on the same file that generated issue 777. Well done!

**Comment by heuermh** [comment]
Thanks @fnothaft, @beaunorgeot

**Pull request merged**
