### PR TITLE
Treat .interval_list file indices as 1-based

### LINKED ISSUE #701: `.interval_list` files should be treated as containing 1-based indices
`IntervalListParser` currently does not handle this correctly.

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #701

### CODE REVIEW

**Comment by fnothaft** [comment]
Age old "off-by-one" error. ;)

**Comment by fnothaft** [comment]
Can you rebase?

**Comment by ryan-williams** [comment]
rebased!

**Comment by fnothaft** [comment]
Thanks @ryan-williams! Merged manually via https://github.com/bigdatagenomics/adam/commit/fe705da62d4efd0da31348b6dd315e93e743fe82.

**Pull request closed without merging**
