### PR TITLE
update recommended Maven MaxPermSize

### LINKED ISSUE #707: Update recommended Maven PermGen settings?
@ipurusho recently ran into PermGen issues ([gist](https://gist.github.com/ipurusho/b1a0a74832a340679cb9)) trying to build ADAM on a clean checkout, with [the recommended `MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=128m"`](https://github.com/bigdatagenomics/adam/blob/4aadaf4e67ffc34f8b9c4580dd555bc2fc976059/README.md#installation).

I noticed that I have `MAVEN_OPTS=-Xmx512m -XX:MaxPermSize=256m` in my `.bashrc`; should we bump the recommended size up?

### PR DESCRIPTION
**Pull request by ryan-williams**
Fixes #707

### CODE REVIEW

**Comment by fnothaft** [comment]
This is showing merge conflicts; can you rebase and resolve the conflicts?

**Comment by ryan-williams** [comment]
heh, I'd made the change in my browser at https://github.com/ryan-williams/adam/blob/master/README.md, but I'd not rebased my fork's master branch in 300+ commits, woops!

**Comment by ryan-williams** [comment]
should be ok now!

**Comment by fnothaft** [comment]
Are you sure you've pushed the rebase? This branch still looks stale...

> I'd not rebased my fork's master branch in 300+ commits, woops!

LOLe.

**Comment by fnothaft** [comment]
Actually, I'm just going to merge this manually. This is a documentation only change, no need to make you fret...

**Comment by fnothaft** [comment]
Thanks @ryan-williams! Manually committed via https://github.com/bigdatagenomics/adam/commit/a94b9c98e314eb1d424859b504b76527df73a97c.

**Comment by ryan-williams** [comment]
Strange, [`perm-size`](https://github.com/ryan-williams/adam/tree/perm-size) seems to be 1 ahead, 1 behind `master` here



git is hard today!

Thanks for merge!

**Pull request closed without merging**
