### PR TITLE
Making join return types consistent

### LINKED ISSUE #1734: Consistency on ShuffleRegionJoin returns
I would like to make consistent the return types for all `ShuffleRegionJoins`, specifically to return `GenericGenomicRDD`s.

### PR DESCRIPTION
**Pull request by devin-petersohn**
Resolves #1734

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM! Thanks @devin-petersohn! I'll leave this open for a day as well, in case @heuermh would like to review.

**Comment by devin-petersohn** [comment]
Please wait to merge until I update pull request.

**Comment by devin-petersohn** [comment]
Ready for review. Sorry for forgetting to delete the `Z` type.

**Comment by heuermh** [comment]
Thank you, @devin-petersohn

**Pull request merged**
