### PR TITLE
bump commons-io version

### PR DESCRIPTION
**Pull request by ryan-williams**
cf. https://github.com/hammerlab/guacamole/pull/444#issuecomment-214047984

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM! Will merge after tests pass.

**Comment by ryan-williams** [comment]
I suppose upgrading further to Hadoop 2.7.0 / Guava 18.0 (as I did in Guacamole) is not desirable here, though, since we're trying to support older versions of Hadoop here?

**Comment by fnothaft** [comment]
> I suppose upgrading further to Hadoop 2.7.0 / Guava 18.0 (as I did in Guacamole) is not desirable here, though, since we're trying to support older versions of Hadoop here?

I think we're holding on 2.6.2 for now.

**Comment by fnothaft** [comment]
Merged. Thanks @ryan-williams!

**Pull request merged**
