### PR TITLE
Add optional accumulator for VCF header lines to VCFOutFormatter.

### PR DESCRIPTION
**Pull request by heuermh**
Required for https://github.com/bigdatagenomics/cannoli/issues/43.

Work in progress, currently Spark 2.x only due to `Accumulator` &rarr; `AccumulatorV2` deprecation.  I suggest waiting until post-0.23.0 when Spark 1.x support is dropped rather than trying to conditionally support both APIs.

### CODE REVIEW

**Comment by heuermh** [comment]
Rebased.

**Comment by fnothaft** [comment]
Ping @heuermh

**Comment by heuermh** [comment]
> have you run this recently on the cluster?

Yes, I've confirmed this works on the cluster.

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!

**Pull request merged**
