### PR TITLE
[ADAM-716] Move to org.apache.parquet:1.7.0.

### LINKED ISSUE #716: Upgrade to Parquet 1.7.0
This is the first `org.apache` release of Parquet.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #716. Depends on the 0.2.2 release of https://github.com/bigdatagenomics/utils, which I am releasing at this very moment.

### CODE REVIEW

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Rebased.

**Comment by laserson** [comment]
lgtm

**Comment by massie** [comment]
Thanks, Frank!

**Pull request merged**
