### PR TITLE
Clean up fields and doc in fragment.

### PR DESCRIPTION
**Pull request by heuermh**
Depends on https://github.com/bigdatagenomics/bdg-formats/pull/162.

### CODE REVIEW

**Comment by heuermh** [comment]
bdg-formats version 0.11.4 has been released, this pull request should be updated when it hits Maven Central.

**Comment by heuermh** [comment]
@akmorrow13 Rebased and ready to merge.

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by akmorrow13** [comment]
thanks @heuermh!

**Pull request merged**
