### PR TITLE
Adding ReadRDD, SequenceRDD, and SliceRDD.

### PR DESCRIPTION
**Pull request by heuermh**
This pull request refactors `NucleotideContigFragment` to `Sequence` and `Slice` and adds new ADAMContext API methods:
```scala
// existing methods
def loadFastq(pathName: String, optPathName2: Option[String] = None, optRecordGroup: Option[String] = None, stringency: ValidationStringency = ValidationStringency.STRICT): AlignmentRecordDataset = {}

def loadPairedFastq(pathName1: String, pathName2: String, optRecordGroup: Option[String] = None, stringency: ValidationStringency = ValidationStringency.STRICT): AlignmentRecordDataset = {}

def loadUnpairedFastq(pathName: String, setFirstOfPair: Boolean = false, setSecondOfPair: Boolean = false, optRecordGroup: Option[String] = None, stringency: ValidationStringency = ValidationStringency.STRICT): AlignmentRecordDataset = {}

def loadInterleavedFastqAsFragments(pathName: String): FragmentDataset = {}

def loadPairedFastqAsFragments(pathName1: String, pathName2: String): FragmentDataset = {}

// new methods
def loadFastaDna(pathName: String): SequenceDataset = {}

def loadFastaProtein(pathName: String): SequenceDataset = {}

def loadFastaRna(pathName: String): SequenceDataset = {}

def loadFastaDna(pathName: String, maximumLength: Long = 10000L): SliceDataset = {}

def loadParquetReads(...): ReadDataset = {}

def loadParquetSequences(...): SequenceDataset = {}

def loadParquetSlices(...): SliceDataset = {}

def loadReads(pathName: String, optPredicate: Option[FilterPredicate], optProjection: Option[Schema] = None): ReadDataset = {}

def loadDnaSequences(pathName: String, optPredicate: Option[FilterPredicate], optProjection: Option[Schema] = None): SequenceDataset = {}

def loadProteinSequences(pathName: String, optPredicate: Option[FilterPredicate], optProjection: Option[Schema] = None): SequenceDataset = {}

def loadRnaSequences(pathName: String, optPredicate: Option[FilterPredicate], optProjection: Option[Schema] = None): SequenceDataset = {}

def loadSlices(pathName: String, maximumLength: Long = 10000L, optPredicate: Option[FilterPredicate], optProjection: Option[Schema] = None): SliceDataset = {}
```

External methods that extend ADAMContext
```scala
def loadGenbankDna(pathName: String): SequenceDataset = {}

def loadGenbankProtein(pathName: String): SequenceDataset = {}

def loadGenbankRna(pathName: String): SequenceDataset = {}

def loadGenbankDna(pathName: String, maximumLength: Long = 10000L): SliceDataset = {}
```
etc.

### CODE REVIEW

**Comment by antonkulaga** [comment]
Is it the PR that should solve my FastConverter problems?

**Comment by heuermh** [comment]
> Is it the PR that should solve my FastConverter problems?

That is the intent; it doesn't yet.  It does allow for https://github.com/heuermh/biojava-adam as a workaround.  I will run some performance comparisons on our cluster on Monday.

**Comment by antonkulaga** [comment]
I do not see this very important issue in the roadmap for 0.25, do you want to release it later?

**Comment by heuermh** [comment]
Sorry, as evident from all the conflicting files, this is a large change and is sensitive to further refactoring.  #1981 is another large one that needs to go first.  They are both milestoned 0.25.0, which has a due date of May 1st.

**Comment by antonkulaga** [comment]
Hope it will be merged soon, waiting 4 hours just to load new mouse transcriptome from the fasta file is killing me!

**Comment by heuermh** [comment]
@antonkulaga Yes, I hope to get this merged this week, it has been sitting around for far too long.

**Pull request merged**
