### PR TITLE
class-ify ShuffleRegionJoin, force setting seqdict

### LINKED ISSUE #697: Remove no-SequenceDictionary API from ShuffleRegionJoin
As discussed on #693, this seems like a dangerous API that confers very little benefit/convenience; [the singleton `sd` instance](https://github.com/bigdatagenomics/adam/blob/2b5c8e959dd5c7a321dfb8d97b9c7b6b08a0eef6/adam-core/src/main/scala/org/bdgenomics/adam/rdd/ShuffleRegionJoin.scala#L32) is also kind of gross and unnecessary.

We should make/let callers compute the `SequenceDictionary`.

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #697

### CODE REVIEW

**Comment by fnothaft** [comment]
As per my comments on #697, I am +1. However, I'm going to hold off on merging this until we cut a 0.17.0 release, and to give @laserson and @tdanford more time to comment.

**Comment by ryan-williams** [comment]
Yea we can discuss more on #697 for the time being…

**Comment by ryan-williams** [comment]
updated this and the description to reflect that it is no longer removing the `RegionJoin` trait, but simply forcing `ShuffleRegionJoin` to be initialized with a `seqDict` and `partitionSize`.

**Comment by ryan-williams** [comment]
this is ready to go, yea @fnothaft? (don't want to pester you while you are at a conference; should I enlist others to merge)?

**Comment by fnothaft** [comment]
I'm about to run to the airport but will have an hour or two there where I would be glad to merge this. Is this rebased on ToT? If not, I'll merge manually.

**Comment by ryan-williams** [comment]
I've got the green "Merge pull request" button here so it is either at ToT or close enough. Update: it is in fact at ToT. (In general if it's close enough that it merges cleanly, do you still care about rebasing?)

**Comment by fnothaft** [comment]
Merged! Thanks @ryan-williams!

> In general if it's close enough that it merges cleanly, do you still care about rebasing?

Yeah, we prefer everything to be rebased before merging in. If all PRs are rebased on ToT before they are merged, we keep a linear commit history. This is IMO a funky design decision in git... In any case, if a PR is small and is _not_ rebased on ToT, we'll manually rebase and merge it.

**Comment by ryan-williams** [comment]
Cool, makes sense.

> This is IMO a funky design decision in git

The allowing of non-linear commit histories, you mean?

**Comment by fnothaft** [comment]
> The allowing of non-linear commit histories, you mean?

Yeah. I mean, obviously this is personal preference but I can't fathom a reason that you'd _want_ a non-linear commit history.

There are also funky design decisions in Github. E.g., the "is this rebased?" question would go away completely if [Github exposed the option to _only allow_ fast forward merges](http://aaronbonner.io/post/78444674979/only-allow-git-fast-forward-merges-to-avoid-ugly). But—god knows why—Github goes the opposite way and disallows fast forward merges via the merge button...

Anyways, this is frankly personal preference. I _mostly_ love git and Github. ;)

**Comment by ryan-williams** [comment]
Makes sense; I've slowly come to want to embrace branching/merging over squashing/rebasing, but it's been a process and taken work.

Github disallowing fast-forward merges, interesting… I guess it doesn't really make sense to merge something that hasn't really been branched (e.g. is an ancestor of `HEAD`)? Good to know…

**Pull request merged**
