### PR TITLE
Update hadoop-bam dependency version to 7.5.0

### PR DESCRIPTION
**Pull request by heuermh**
Will update to version 7.5.0 as appropriate on its release.

### CODE REVIEW

**Comment by heuermh** [comment]
```bash
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-versions) @ adam-parent_2.10 ---
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
ADAM requires Java 1.8 or greater
```
Looks like we'll need to update the JDK on our Jenkins box.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Well, this is strange.
```
...
[EnvInject] - Injecting as environment variables the properties content 
JAVA_HOME=/usr/java/jdk1.8.0_60
PATH=/usr/java/jdk1.8.0_60/bin/:/home/anaconda/bin:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.1.1/bin/:/home/android-sdk/:/usr/local/bin:/bin:/usr/bin

[EnvInject] - Variables injected successfully.
[centos] $ /bin/bash /tmp/hudson1618264243236400584.sh
/usr/java/jdk1.8.0_60
/home/jenkins/tools/hudson.model.JDK/JDK_7u60/bin:/usr/java/jdk1.8.0_60/bin/:/home/anaconda/bin:/home/jenkins/tools/hudson.tasks.Maven_MavenInstallation/Maven_3.1.1/bin/:/home/android-sdk/:/usr/local/bin:/bin:/usr/bin
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
/home/jenkins/tools/hudson.model.JDK/JDK_7u60/bin/java
```

**Comment by fnothaft** [comment]
That's me going through and testing. The TL;DR from my tests is that Jenkins prepends `$JAVA_HOME` to `$PATH` when running Maven, which is all sorts of a hassle.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Woot!

**Comment by fnothaft** [comment]
Great! H/T to @shaneknapp for help getting Java 8 working. I will have a follow up PR (see #1008) that pulls the workarounds into our repo.

**Comment by heuermh** [comment]
The question then is whether to merge this with a snapshot dependency on Hadoop-BAM or wait until the next release is available.  Reports on gitter are that this branch may not help the gzipped/bgzipped VCF problem (yet).

**Comment by fnothaft** [comment]
@heuermh discussed the snapshot dependency and will reach out to @tomwhite & @AndreSchumacher to see when a new Hadoop-BAM release will be cut.

**Comment by heuermh** [comment]
The BCF-related unit tests will fail due to https://github.com/samtools/htsjdk/issues/507.

**Comment by fnothaft** [comment]
Merged. Thanks @heuermh!

**Comment by heuermh** [comment]
Thank you, sir

**Pull request merged**
