### PR TITLE
[ADAM-752] update spark compile dependency to version 1.4.1

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by ryan-williams** [comment]
Thanks @heuermh; how confident are we that jenkins passing means we don't think there are notable transitive-dep concerns? I'm inclined to trust it and try to add tests if we discover issues we hadn't anticipated.

**Comment by heuermh** [comment]
I feel pretty good about the Jenkins tests, since it not only runs unit tests but calls ```adam-submit``` (commands ```transform```, ```transform -sort```, ```reads2ref```, ```print```, and ```flagstat```).

**Comment by heuermh** [comment]
Woot!  Thank you, Mr Jenkins, sir.

**Comment by fnothaft** [comment]
LGTM!

**Pull request merged**
