### PR TITLE
Upgrade to bdg-formats-0.10.0

### PR DESCRIPTION
**Pull request by fnothaft**
For tracking.

### CODE REVIEW

**Comment by fnothaft** [comment]
-1, not yet ready to merge.

**Comment by fnothaft** [comment]
Rebased. CC @heuermh

**Comment by heuermh** [comment]
@fnothaft could you rebase this?

**Comment by fnothaft** [comment]
Had to update some test collateral. This should pass on this build.

**Comment by heuermh** [comment]
Right, the unit test failures here are due to filter-related changes.  I'm not sure why I didn't run into these on #1250.

**Comment by fnothaft** [comment]
> Right, the unit test failures here are due to filter-related changes. I'm not sure why I didn't run into these on #1250.

I was scratching my head there for a bit too, but then I realized it was because we had added said tests more recently than the last time we rebased this branch.

**Comment by fnothaft** [comment]
Merged! Huge tip of the hat to @heuermh for leading this refactor.

**Pull request merged**
