### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### bigdatagenomics/adam now has a Chat Room on Gitter

@massie has just created a chat room. You can visit it here: [https://gitter.im/bigdatagenomics/adam](https://gitter.im/bigdatagenomics/adam?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/bigdatagenomics/adam?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by laserson** [comment]
This could use a couple extra line breaks I think

**Comment by laserson** [comment]
@massie How do I make a change to the PR?  I don't know if I have permissions.

**Comment by gitter-badger** [comment]
How about now?

**Comment by fnothaft** [comment]
Manually committed via https://github.com/bigdatagenomics/adam/commit/20b621db75179abcd20478d382784b547fa0edf0.

**Pull request closed without merging**
