### PR TITLE
adam2vcf doesn't have info fields

### PR DESCRIPTION
**Pull request by andrewmchen**
I added info fields only if the vcf is from a single sample.

What's the desired behavior if the vcf has multiple samples per site?

### CODE REVIEW

**Comment by fnothaft** [comment]
Whoops! You should have an info field per site, as well as sample specific annotations (per sample, per site), see https://samtools.github.io/hts-specs/VCFv4.2.pdf. Essentially, the info field behavior should be the same in the single and multi sample cases.

**Comment by andrewmchen** [comment]
Hm I read through the VCF spec and I don't think I completely understand still. 

First, my understanding was that before this PR we wouldn't have any per site info field. Second, when convert a VCF to a RDD of adam Genotypes, are the VariantCallingAnnotations statistics not per sample but instead statistics aggregated across samples from that site?

**Comment by heuermh** [comment]
@andrewmchen after we get 0.19.0 out, I plan to focus on VCF INFO handling, for supporting the VCF ANN spec and other related issues.  Please let me know how I might help in a week or so.

**Comment by andrewmchen** [comment]
@heuermh Sure! Would love to work with you on some of the VCF features. Right now I'm just playing around with it for the purposes of avocado. 

Maybe this isn't the desired behavior, but I think it's kind of strange that adam2vcf returns a much different vcf than the original that was passed into vcf2adam. Are the related issues you mentioned related to this?

**Comment by fnothaft** [comment]
I will open a follow on PR that addresses some issues with this (specifically, stores sample info in genotype, aggregate in INFO).

**Comment by fnothaft** [comment]
@heuermh is this good to go on your side? I just looked in more detail and think it is fine (doesn't need any more patches). If it is good from your side, then I will merge.

**Comment by heuermh** [comment]
LGTM

**Comment by fnothaft** [comment]
Merged! Thanks @andrewmchen!

**Pull request merged**
