### PR TITLE
[ADAM-755] updating utils dependency version to 0.2.3, fixes #755

### LINKED ISSUE #755: Help pages for CLI are messed up
See

```
$ adam/bin/adam-submit -- vcf2adam --help
15/08/04 21:13:21 INFO cli.ADAMMain: ADAM invoked with args: "vcf2adam" "--help"
 -h (-help, --help, -?)                                          : Print help
 -parquet_block_size N                                           : Parquet block size (default = 128mb)
 -parquet_compression_codec [UNCOMPRESSED | SNAPPY | GZIP | LZO] : Parquet compression codec
 -parquet_disable_dictionary                                     : Disable dictionary encoding
 -parquet_logging_level VAL                                      : Parquet logging level (default = severe)
 -parquet_page_size N                                            : Parquet page size (default = 1mb)
 -print_metrics                                                  : Print metrics to the log on completion
```

vs

```
$ adam/bin/adam-submit -- vcf2adam
15/08/04 21:13:30 INFO cli.ADAMMain: ADAM invoked with args: "vcf2adam"
Argument "VCF" is required
 VCF                                                             : The VCF file to convert
 ADAM                                                            : Location to write ADAM Variant data
 -coalesce N                                                     : Set the number of partitions written to the ADAM output directory
 -dict FILE                                                      : Reference dictionary
 -h (-help, --help, -?)                                          : Print help
 -onlyvariants                                                   : Output Variant objects instead of Genotypes
 -parquet_block_size N                                           : Parquet block size (default = 128mb)
 -parquet_compression_codec [UNCOMPRESSED | SNAPPY | GZIP | LZO] : Parquet compression codec
 -parquet_disable_dictionary                                     : Disable dictionary encoding
 -parquet_logging_level VAL                                      : Parquet logging level (default = severe)
 -parquet_page_size N                                            : Parquet page size (default = 1mb)
 -print_metrics                                                  : Print metrics to the log on completion
```

When adding the `--help` flag, I only get info on the Parquet args.

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by ryan-williams** [comment]
any known issues with this bump?

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Oops, sorry Jenkins, wrong pull request.  :)

**Comment by massie** [comment]
Is this ready to merge? I see a question from @ryan-williams that hasn't been addressed. Ryan, is there something in particular that you're concerned about with this bump?

Related: I went to look at the diff on github and noticed that the tag name syntax changed. I'm assuming that's intensional?

screen shot 2015-08-26 at 5 11 17 pm

**Comment by fnothaft** [comment]
LGTM.

> Related: I went to look at the diff on github and noticed that the tag name syntax changed. I'm assuming that's intensional?

Correct; that is intentional.

**Comment by fnothaft** [comment]
Also, just to respond to @ryan-williams upstream, there are no known issues with utils:0.2.3.

**Comment by fnothaft** [comment]
Thanks @heuermh! I've merged this as 5432a61c0241519b390ad31569cd965a9b604b0b.

**Pull request closed without merging**
