### PR TITLE
[ADAM-1371] Wrap ADAM->htsjdk VariantContext conversion with validation stringency.

### LINKED ISSUE #1371: Bits of VariantContextConverter don't get ValidationStringencied
E.g., https://github.com/bigdatagenomics/adam/blob/master/adam-core/src/main/scala/org/bdgenomics/adam/converters/VariantContextConverter.scala#L1923 does not get a validation stringency check.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1371. Could use some more unit tests; will make a pass back later.

### CODE REVIEW

**Comment by heuermh** [comment]
I was thinking this might help with htsjdk exceptions like those in #1351, and added unit tests for it, but the exception is apparently thrown elsewhere
```scala
  sparkTest("VCF file with invalid alleles silent stringency") {
    val path = testFile("ExAC.0.3.GRCh38.invalid-allele.vcf")
    val vcs = sc.loadVcf(path, stringency = ValidationStringency.SILENT)
    assert(vcs.rdd.count == 5)
  }
```

```
- VCF file with invalid alleles silent stringency *** FAILED ***
  org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 401: Duplicate allele added to VariantContext: A
	at htsjdk.variant.vcf.AbstractVCFCodec.generateException(AbstractVCFCodec.java:779)
	at htsjdk.variant.vcf.AbstractVCFCodec.parseVCFLine(AbstractVCFCodec.java:356)
	at htsjdk.variant.vcf.AbstractVCFCodec.decodeLine(AbstractVCFCodec.java:279)
	at htsjdk.variant.vcf.AbstractVCFCodec.decode(AbstractVCFCodec.java:257)
	at org.seqdoop.hadoop_bam.VCFRecordReader.nextKeyValue(VCFRecordReader.java:144)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:179)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.util.Utils$.getIteratorSize(Utils.scala:1631)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$count$1.apply(RDD.scala:1157)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1858)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by fnothaft** [comment]
Yep; where is your god now, eh?

**Comment by heuermh** [comment]
Want to merge this as is then?  I'm no longer in the mood to write unit tests for it  :)

**Comment by fnothaft** [comment]
I have a unittest in mind, but won't be able to get to it until this weekend. Are you OK with waiting until next week to merge? If not, let's merge as is.

**Comment by heuermh** [comment]
This can wait; I pushed up the failing tests as https://github.com/heuermh/adam/commit/57f0895af7e2be561a05109dfc103b8e6f866a2c in case they might come in handy later

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
