### PR TITLE
[ADAM-452] Fixes SM attribute on ADAM to BAM conversion.

### LINKED ISSUE #452: "SM" BAM attribute being set incorrectly?
I noticed ADAM outputting BAMs with records' "SM" attr [set to the "recordGroupSample" value](https://github.com/bigdatagenomics/adam/blob/9bd74c87908a97ccdc23c3c6198a9a080f041e34/adam-core/src/main/scala/org/bdgenomics/adam/converters/AlignmentRecordConverter.scala#L76).

The [SAM spec](http://samtools.github.io/hts-specs/SAMv1.pdf) implies that "SM" is intended to be an integer, and represent "Template-independent mapping quality":

Not a very important-seeming discrepancy, but I thought I'd document it here in case there's some interesting reason for this, or whether we should change it.

### PR DESCRIPTION
**Pull request by andrewmchen**
Resolves #452. Small change that stops setting SM attribute to recordGroupSample in ADAM to BAM conversion.

### CODE REVIEW

**Comment by massie** [comment]
Add to whitelist. Jenkins, test this please.

**Comment by fnothaft** [comment]
@andrewmchen looks good! Can you add unit tests to validate the change?

**Comment by andrewmchen** [comment]
I added some unit tests in a new commit and squashed everything down to one commit.

**Comment by massie** [comment]
:+1:

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Merged! Thanks @andrewmchen!

**Pull request merged**
