### PR TITLE
added adam notebook

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by fnothaft** [comment]
This is awesome! Would it be possible to add an example notebook, and to add some docs around this?

**Comment by akmorrow13** [comment]
Definitely! Should In Mango, I have an example-files where I put some example-notebooks based on test resource files. Would we prefer to do that or reference the our test s3 bucket?

**Comment by fnothaft** [comment]
My preference is to add a `scripts/examples`, and to then run `adam-notebook` with the example script from within `scripts/jenkins_test`. Two birds, one stone.

**Comment by akmorrow13** [comment]
I can do that. What I have been doing is converting example-notebooks to py files and testing them in the unit tests. That way, the local tests also catch errors. Either way works though.

**Comment by fnothaft** [comment]
Unless we have unit test coverage gaps that the example notebook would catch, I'd rather have the example notebook run through the `adam-notebook` command so we can catch any regressions in `bin/adam-notebook`.

**Comment by akmorrow13** [comment]
I'm not sure how you would run an ipython notebook in jenkins test.

**Comment by heuermh** [comment]
Python on Juypter is one flavor of ADAM notebook, do we want to commit to that as the `adam-notebook`?

**Comment by akmorrow13** [comment]
Jenkins, retest this please.

**Comment by akmorrow13** [comment]
There are 2 issues here:
1. I cannot test adam-notebook in the regression tests. This is because it spawns a new process and is accessible through the browser, which jenkins cannot access.
2. @fnothaft asked to add some example notebooks. However, I don't know what data to access for examples. We can't use data in the resource directories because then the examples will not work in the distribution. Any ideas?

**Comment by akmorrow13** [comment]
Closing, as duplication in https://github.com/bigdatagenomics/mango/blob/master/bin/mango-notebook

**Pull request closed without merging**
