### PR TITLE
Add direct conversion from DatasetBoundFragmentRDD to DatasetBoundAli…

### PR DESCRIPTION
**Pull request by henrydavidge**
…gnmentRecordRDD

This PR overrides `toReads()` on a `DatasetBoundFragmentRDD` to do the transformation to an `AlignmentRecordRDD` in SQL, which skips two rounds of unnecessary conversion if you're going to query on the dataset of reads afterward.

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, add to whitelist.

**Comment by heuermh** [comment]
@henrydavidge Thanks for the contribution!  You shouldn't need to merge commit in a pull request; can you reapply your changes on top of HEAD?

Looking at the first commit, I would guess any merge conflicts are due to your import statement reformatting.  Consider fixing your IDE so that it doesn't do that!  :wink:

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
@fnothaft could you take care of the merge on this one?

**Comment by heuermh** [comment]
Closing in favor of #2162

**Pull request closed without merging**
