### PR TITLE
[ADAM-1834] Add proper extensions for SAM/BAM/CRAM output formats.

### LINKED ISSUE #1834: Specify correct extensions for SAM/BAM output
See https://github.com/HadoopGenomics/Hadoop-BAM/pull/176.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1834.

### CODE REVIEW

**Comment by heuermh** [comment]
Does this completely resolve #1834 or do we also need https://github.com/HadoopGenomics/Hadoop-BAM/pull/176?  I'm not sure exactly how the issue manifests itself.

**Comment by fnothaft** [comment]
We need https://github.com/HadoopGenomics/Hadoop-BAM/pull/176 for VCF.

**Comment by heuermh** [comment]
> We need HadoopGenomics/Hadoop-BAM#176 for VCF.

I see, thanks.

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
