### PR TITLE
Remove dependency on parquet-scala

### PR DESCRIPTION
**Pull request by karenfeng**
As mentioned in #2108 , the available version of parquet-scala is stuck in 2.10. The cleanest way to get around this issue is probably to just remove this dependency.

### CODE REVIEW

**Comment by heuermh** [comment]
Thank you, @karenfeng.  This is a reasonable idea, as it doesn't look like the issue will be resolved upstream (i.e. there are two pull requests in parquet-mr and neither appear to be close to being merged).

The Jenkins failure seen here requires #2140 to be merged.  I'll trigger a new build here when that happens.

**Comment by heuermh** [comment]
Hello @karenfeng, sorry but to pick up the changes in #2140, you'll need to rebase this pull request branch against master.

**Comment by heuermh** [comment]
Ping @ryan-williams, would you agree this is better than waiting for changes in parquet-mr?

**Comment by ryan-williams** [comment]
This just uses the Parquet Java APIs? That seems like a good workaround to me! Nice work @karenfeng

**Comment by heuermh** [comment]
Thank you, @karenfeng

**Pull request merged**
