### PR TITLE
[ADAM-1322] Skip git commit plugin if .git is missing.

### LINKED ISSUE #1322: adam-cli uses git-commit-id-plugin which breaks release?
I just downloaded [a release](https://github.com/bigdatagenomics/adam/archive/adam-parent-spark2_2.11-0.20.0.tar.gz) of ADAM and tried to run `mvn package -DskipTests` which failed on the ADAM CLI module with 

```
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.1:revision (default) on project adam-cli-spark2_2.11: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]
```

Is this expected?

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1322.

### CODE REVIEW

**Comment by fnothaft** [comment]
Hold on merging; going to build and test locally.

**Comment by fnothaft** [comment]
This is good to go. If you build without a .git directory, you get:

```
./bin/adam-submit --version
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-1.5.2//bin/spark-submit

       e         888~-_          e             e    e
      d8b        888   \        d8b           d8b  d8b
     /Y88b       888    |      /Y88b         d888bdY88b
    /  Y88b      888    |     /  Y88b       / Y88Y Y888b
   /____Y88b     888   /     /____Y88b     /   YY   Y888b
  /      Y88b    888_-~     /      Y88b   /          Y888b

ADAM version: 0.20.1-SNAPSHOT
Commit: ${git.commit.id} Build: 2016-12-22
Built for: Scala 2.10.6 and Hadoop 2.7.3
```

**Comment by fnothaft** [comment]
Ping for review/merge.

**Comment by heuermh** [comment]
Sure, will give it a test this evening when I'm not so distracted.

**Comment by fnothaft** [comment]
Sounds good, thanks.

**Comment by heuermh** [comment]
This works for me.

I want to modify About/ADAMMain so that if the commit template variable hasn't been set that the `Commit: ...` line isn't displayed, will send a PR later today.

**Comment by fnothaft** [comment]
> I want to modify About/ADAMMain so that if the commit template variable hasn't been set that the Commit: ... line isn't displayed, will send a PR later today.

Good call; will look out for the PR.

**Comment by heuermh** [comment]
Sorry, I'm an idiot, there's already
```scala
if (about.isSnapshot) { ...
```

**Pull request merged**
