### PR TITLE
[ADAM-1328] Rename `Transform` to `TransformAlignments`.

### LINKED ISSUE #1328: Rename Transform command TransformAlignments or similar
With new commands `TransformFeatures`, `TransformGenotypes`, and `TransformVariants`, the original `Transform` command should be renamed `TransformAlignmentRecords` or `TransformAlignments` or `TransformReads` or similar.

See also #1178

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1328.

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
https://github.com/bigdatagenomics/adam/blob/master/scripts/jenkins-test#L221 also needs a change

**Comment by fnothaft** [comment]
Thanks @heuermh ; just fixed.

**Comment by fnothaft** [comment]
@heuermh can you merge?

**Comment by heuermh** [comment]
I was thinking of pinging folks downstream about this one and #1532 to make sure the CLI changes don't cause too much trouble.  I'll do that tomorrow.

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
