### PR TITLE
[ADAM-1124] Add Scoverage and generate coverage reports in Jenkins.

### LINKED ISSUE #1124: Generate Scoverage reports when running CI
See https://github.com/hammerlab/guacamole/pull/564

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1124. H/T @ryan-williams, "If I have seen further, it is by standing on the shoulders of giants.", etc, etc. ;)

### CODE REVIEW

**Comment by fnothaft** [comment]
Scoverage appears to only work on Scala 2.10.

**Comment by ryan-williams** [comment]
that is a bummer… i was going to try to 2.11 guacamole soon so can take a look again then :-\

**Comment by fnothaft** [comment]
Actually, it says that scoverage supports Scala 2.11. I'm guessing this is an issue in the Maven plugin. I'll dig into this a bit more.

**Comment by fnothaft** [comment]
Actually, what I said about Scala 2.11 is completely wrong. The scala 2.11 build was running a-OK, scala 2.10 was failing.

**Comment by fnothaft** [comment]
...which is interesting, because I built on Scala 2.10.4 locally?

**Comment by fnothaft** [comment]
Looks like the issue was https://github.com/scoverage/sbt-scoverage/issues/86. I've just aborted the last run with this fix in. Hopefully, this is a go!

**Comment by fnothaft** [comment]
Fixed a typo I added to the `jenkins-test` script.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Sweet! This works in Jenkins now; we get code coverage plots and all. The one caveat is that it only displays the `adam-core` coverage stats. The Jenkins Scoverage plugin only supports a single `scoverage.xml` file. We'll have to manually look at coverage for `adam-apis` and `adam-cli`, but this is a step in the right direction.

**Comment by fnothaft** [comment]
Coverage data shows up on the pages that correspond to a specific version in our matrix, e.g., --> https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/HADOOP_VERSION=2.6.0,SCALAVER=2.10,SPARK_VERSION=1.5.2,label=centos/

**Comment by fnothaft** [comment]
Ping for merge. Would be nice to get this in, so we can get coverage reported for all PRs afterwards...

**Comment by heuermh** [comment]
I'm not seeing any scoverage reports on jenkins, even for those build #s associated with this pull request

https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/1415/HADOOP_VERSION=2.6.0,SCALAVER=2.10,SPARK_VERSION=1.5.2,label=centos/scoverage-report/
https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/1416/HADOOP_VERSION=2.6.0,SCALAVER=2.10,SPARK_VERSION=1.5.2,label=centos/scoverage-report/

**Comment by heuermh** [comment]
This one will need a rebase after #1127; please let me know if perhaps I'm looking in the wrong place for the scoverage reports.

**Comment by fnothaft** [comment]
@heuermh look at the build now: https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/HADOOP_VERSION=2.6.0,SCALAVER=2.10,SPARK_VERSION=1.5.2,label=centos/

The coverage stats go away if the last build did not have a coverage report attached. This is what I see:

screen shot 2016-08-25 at 3 44 10 pm

**Comment by heuermh** [comment]
I see!  The link on the left side of the page (Scoverage HTML Report) is what 404s.
https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/HADOOP_VERSION=2.6.0,SCALAVER=2.10,SPARK_VERSION=1.5.2,label=centos/scoverage

**Comment by fnothaft** [comment]
> I don't see that as a problem with this pull request though, more some kind of Jenkins UI configuration or Jenkins plugin problem.

Yeah, the Jenkins Scoverage plugin is... just OK. Not great, just OK.

**Comment by heuermh** [comment]
LGTM

**Comment by heuermh** [comment]
Merged as commit daf524638e77ef8abef830ac23ad3ad80dbf7b79.

Thank you, @fnothaft, @ryan-williams!

**Comment by fnothaft** [comment]
Thanks for merging, @heuermh! May our coverage forever increase.

**Pull request merged**
