### PR TITLE
[ADAM-528][ADAM-533] Adds new RegionJoin impl that is shuffle-based

### LINKED ISSUE #528: Add RegionJoin impl that is shuffle/partition-based
This will be a distributed analog of the overall technique in bedtools2.  The partitioning strategy is based off of the one described in Jim Kent's Genome Browser paper (Figure 7) [1].  Still not sure exactly of the details, but from a high level, the genome is hierarchically partitioned into a k-adic tree of ranges: the deepest level of the tree has the smallest partition sizes.  Each `ReferenceRegion` object is then assigned (keyed) to the smallest node in the tree that will fit the entire region.  The idea is that, hopefully, most of the data will be in the deepest leaf nodes.  The join ultimately requires performing cross-products and filters for each compatible bucket between the two data sets.  Nodes on the same level obviously match with each other, but overlapping nodes from higher levels must also be joined.  Hopefully the amount of data in the higher levels remains relatively small.  Depending on implementation, a certain level up the tree may be best served with a broadcast, while the lower levels are shuffled.  Significantly, this implementation avoids collecting and broadcasting a whole side of the join.

Thoughts before I begin?

[1]: http://genome.cshlp.org/content/12/6/996.full

### LINKED ISSUE #533: Rename `GenomicRegionPartitioner` to `GenomicPositionPartitioner`
This partitioner only handles `ReferencePosition` objects.  I will implement a separate partitioner that will handle and `ReferenceRegion`able when I do #528.

### PR DESCRIPTION
**Pull request by laserson**
First pass shuffle-based join impl.  Passes some rudimentary tests.

Certainly needs docs and more tests.

Fixes #528.
Fixes #533.

### CODE REVIEW

**Comment by laserson** [comment]
@tdanford @fnothaft What is necessary to move this forward?  I added scaladocs, and there are some tests, though there could be more.  One issues is I made a few changes that I thought would be relatively cosmetic, and now the build hangs with some Akka problem.  Any idea what's going on here?

```
2015-01-05 18:36:27 ERROR OneForOneStrategy:66 - Actor not found for: ActorSelection[Anchor(akka.tcp://sparkDriver@localhost:7077/), Path(/user/HeartbeatReceiver)]
akka.actor.ActorInitializationException: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:164)
	at akka.actor.ActorCell.create(ActorCell.scala:596)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263)
	at akka.dispatch.Mailbox.run(Mailbox.scala:219)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: akka.actor.ActorNotFound: Actor not found for: ActorSelection[Anchor(akka.tcp://sparkDriver@localhost:7077/), Path(/user/HeartbeatReceiver)]
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:65)
	at akka.actor.ActorSelection$$anonfun$resolveOne$1.apply(ActorSelection.scala:63)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.unbatchedExecute(Future.scala:74)
	at akka.dispatch.BatchingExecutor$class.execute(BatchingExecutor.scala:110)
	at akka.dispatch.ExecutionContexts$sameThreadExecutionContext$.execute(Future.scala:73)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:267)
	at akka.actor.EmptyLocalActorRef.specialHandle(ActorRef.scala:508)
	at akka.actor.DeadLetterActorRef.specialHandle(ActorRef.scala:541)
	at akka.actor.DeadLetterActorRef.$bang(ActorRef.scala:531)
	at akka.remote.RemoteActorRefProvider$RemoteDeadLetterActorRef.$bang(RemoteActorRefProvider.scala:87)
	at akka.remote.EndpointWriter.postStop(Endpoint.scala:561)
	at akka.actor.Actor$class.aroundPostStop(Actor.scala:475)
	at akka.remote.EndpointActor.aroundPostStop(Endpoint.scala:415)
	at akka.actor.dungeon.FaultHandling$class.akka$actor$dungeon$FaultHandling$$finishTerminate(FaultHandling.scala:210)
	at akka.actor.dungeon.FaultHandling$class.terminate(FaultHandling.scala:172)
	at akka.actor.ActorCell.terminate(ActorCell.scala:369)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
	... 8 more
```

**Comment by fnothaft** [comment]
I'm good with merging once the tests pass; I can give the test issue a look tomorrow.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by laserson** [comment]
Jenkins, retest this please.

**Comment by laserson** [comment]
@fnothaft well there you go

**Comment by laserson** [comment]
@fnothaft @tdanford ok, please review, and let me know if there are some other things to do before merging :)

**Comment by fnothaft** [comment]
I am +1 to merge.

**Comment by laserson** [comment]
@fnothaft Is it uncouth to merge my own PR after it's +1'd?

**Comment by fnothaft** [comment]
@laserson resolved that problem for you ;). Thanks for the contribution!

**Pull request merged**
