### PR TITLE
[ADAM-1597] Move to Scala 2.11 and Spark 2.x.

### LINKED ISSUE #1597: RFC: Removing Spark 1.x, Scala 2.10 support in 0.24.0 release
[From the spark-dev list, it looks like Spark 2.3.0 will add support for Scala 2.12 and drop support for Scala 2.10.](http://apache-spark-developers-list.1001551.n3.nabble.com/RFC-removing-Scala-2-10-td21116.html) As such, I think that we should drop Spark 1.x and Scala 2.10 support in the first ADAM release after Spark 2.3.0, which for now, I am assuming to be ADAM 0.24.0. Thoughts?

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1597.

- [x] Move poms to Scala 2.11 and Spark 2.x.
- [x] Remove `move_to_scala_2.10.sh` and `move_to_spark_1.sh` scripts.
- [x] Update `jenkins-test` not to call move scripts unnecessarily.
- [x] Update `release.sh` to only build and release Scala 2.11 and Spark 2.x.
- [x] Update Scala dependency to the latest 2.11.x.
- [x] Update Spark dependency to the latest 2.2.x.
- [x] Update Jenkins build matrix configuration and `jenkins-test` to match Scala and Spark dependency versions.
- [x] Update README as necessary.
- [x] Update documentation as necessary.

I'd like to leave as much of the pom re-writing in place as possible so that when Spark goes to version 3 or starts releasing for Scala 2.12 we'll be able to handle it smoothly.

### CODE REVIEW

**Comment by fnothaft** [comment]
Thoughts on dropping spark2 from the artifact names? My preference is to nix it, but I can see the argument of keeping them in favor of consistency.

**Comment by heuermh** [comment]
I was thinking of leaving spark2 in there for when spark3 comes along.

**Comment by fnothaft** [comment]
> I was thinking of leaving spark2 in there for when spark3 comes along.

SGTM!

**Comment by fnothaft** [comment]
@heuermh I've bumped the Jenkins build version for you.

**Comment by heuermh** [comment]
Looks like the cloudfront URLs we were using to bypass the Apache mirror script aren't working for Spark 2.2.1.

```
$ wget http://d3kbcqa49mib13.cloudfront.net/spark-2.2.1-bin-hadoop2.7.tgz
--2018-01-05 15:12:25--  http://d3kbcqa49mib13.cloudfront.net/spark-2.2.1-bin-hadoop2.7.tgz
Resolving d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)... 52.222.218.79, 52.222.218.77, 52.222.218.190, ...
Connecting to d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)|52.222.218.79|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-05 15:12:25 ERROR 404: Not Found.

$ wget http://d3kbcqa49mib13.cloudfront.net/spark-2.2.1-bin-hadoop2.6.tgz
--2018-01-05 15:12:29--  http://d3kbcqa49mib13.cloudfront.net/spark-2.2.1-bin-hadoop2.6.tgz
Resolving d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)... 52.222.218.79, 52.222.218.77, 52.222.218.190, ...
Connecting to d3kbcqa49mib13.cloudfront.net (d3kbcqa49mib13.cloudfront.net)|52.222.218.79|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-01-05 15:12:29 ERROR 404: Not Found.
```

**Comment by fnothaft** [comment]
Indeed; Spark 2.2.1 is not in the cloudfront bucket. IIRC, they stopped listing the direct download link due to Apache frowning on the process.

**Comment by heuermh** [comment]
I'm not sure what to do with `cgcloud.rst`.  The Input and Output data on HDFS and S3 and later sections are worthwhile, perhaps we modify `cgcloud.rst` into a generic running on AWS page?  I'd like to add EMR doc, but this PR shouldn't be tied to that.

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!

**Pull request merged**
