### PR TITLE
Update jenkins script to test python 3.6

### PR DESCRIPTION
**Pull request by Georgehe4**

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by heuermh** [comment]
Jenkins, add to whitelist

**Comment by heuermh** [comment]
Sorry about the close, hit the wrong button

**Comment by akmorrow13** [comment]
@Georgehe4 Jenkins is failing with  `java.lang.OutOfMemoryError: Java heap space`. Did you say you were getting a different local error?

**Comment by akmorrow13** [comment]
Closing, rebased with https://github.com/bigdatagenomics/adam/pull/2070/files

**Pull request closed without merging**
