### PR TITLE
include SequenceRecords from second-in-pair reads

### LINKED ISSUE #693: Sequence dictionaries should include SequenceRecords from second-in-pair reads
I just hit an error:
```
htsjdk.samtools.SAMFormatException: Error parsing text SAM file. MRNM 'chr10' not found in any SQ record; Line 152
```
trying to load a SAM file, output by ADAM, that contains an `@SQ` record for the contig the read in question is on ("chr11"), but not that of its mapped mate ("chr10").

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #693

### CODE REVIEW

**Comment by fnothaft** [comment]
SGTM! Squash down and I'll merge after tests pass?

**Comment by ryan-williams** [comment]
k, will do. Now that the build has started, can the squash/force-push mess it up? Is that how we end up with some versions succeeding and others failing?

**Comment by fnothaft** [comment]
Nah, the current build will be unaffected. I wouldn't worry about the squash/force-push issue; it's a transient bug and can be resolved just by rerunning.

**Comment by ryan-williams** [comment]
squashed!

**Comment by fnothaft** [comment]
Thanks! Can you rebase?

**Comment by ryan-williams** [comment]
rebased!

**Comment by laserson** [comment]
lgtm

**Comment by ryan-williams** [comment]
bump!

**Comment by ryan-williams** [comment]
rebased once more

**Comment by fnothaft** [comment]
Merged! Thanks @ryan-williams!

**Pull request merged**
