### PR TITLE
Fastq record converter

### PR DESCRIPTION
**Pull request by fnothaft**
Moving @zyxue's work over from #1185, but squashed down and with @heuermh's review comments in.

### CODE REVIEW

**Comment by fnothaft** [comment]
I will merge on tests passing.

**Comment by zyxue** [comment]
@heuermh has added some more requests, I haven't got a chance to look into it yet. Will do later.

**Comment by fnothaft** [comment]
Hi @zyxue! We're trying to get a release of ADAM out tomorrow, and we wanted to get your work on #1185 in to that release, so I added a commit here to address @heuermh's comments. Thanks again for all your hard work on the code!

**Comment by zyxue** [comment]
I see, I can try to incorporate them tonight (Pacific time). I think @heuermh has some good comment that's worth looking into. You can run a test later, if that's not too late?

**Comment by fnothaft** [comment]
Squashed and merged as df00eff150a04d4d7e8cfe9f5749373e8521983c. Thanks @zyxue for the contribution!

**Comment by fnothaft** [comment]
> I see, I can try to incorporate them tonight (Pacific time). I think @heuermh has some good comment that's worth looking into. You can run a test later, if that's not too late?

Not to worry! I was able to address @heuermh's comments here (and test them as well) real quick. Thanks again for the contribution; we appreciate you taking the time to contribute the code and are glad that you were able to patch up this issue for us!

**Comment by zyxue** [comment]
OK, Thanks! ADAM is a good project! I am glad that I can contribute.

**Comment by heuermh** [comment]
@zyxue thank you for your contribution, and thank you for your patience through the process, sometimes Jenkins can be a bit flaky.

**Pull request closed without merging**
