### PR TITLE
Add -print_metrics option to Jenkins build

### PR DESCRIPTION
**Pull request by heuermh**
I expect this may fail.

### CODE REVIEW

**Comment by heuermh** [comment]
Not exactly what I would've expected.

Looks like there is an unrelated Spark 1.5.2 build --> 1.2.1 runtime incompatibility
```
java.lang.NoClassDefFoundError: org/apache/spark/rdd/RDD$
  at org.apache.spark.rdd.InstrumentedOrderedRDDFunctions
    .sortByKey(InstrumentedOrderedRDDFunctions.scala:35)
  at org.bdgenomics.adam.rdd.read.AlignmentRecordRDDFunctions$$anonfun
    $adamSortReadsByReferencePosition$1.apply(AlignmentRecordRDDFunctions.scala:662)
```
and inconsistent failures elsewhere due to execution problems
```
java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
```
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost): java.io.IOException: org.apache.spark.SparkException: Failed to get broadcast_0_piece0 of broadcast_0
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1178)
	at org.apache.spark.broadcast.TorrentBroadcast.readBroadcastBlock(TorrentBroadcast.scala:165)
```
Perhaps calling ```ADAMMain.main(...)``` isn't compatible with our test suite, although it works for me locally.

**Comment by heuermh** [comment]
@fnothaft @massie I can't tell what's going wrong here.

I am not able to reproduce these ```SparkException: Failed to get broadcast_0_piece0 of broadcast_0``` exceptions when running ```scripts/jenkins-test``` locally.

**Comment by massie** [comment]
The underlying issue seems to be having multiple Spark contexts running in a single JVM. It's possible that Jenkins is running the tests differently than when you run them locally (e.g. in a single JVM vs. threaded).

**Comment by heuermh** [comment]
It must be problem with the unit tests then.
I'll have to find a way to exercise ```-print_metrics``` without going through ```ADAMMain.main(...)```.

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Ready to merge, ```-print-metrics``` works for me locally across our current build matrix.

**Comment by fnothaft** [comment]
Thanks @heuermh! Merged.

**Pull request merged**
