### PR TITLE
[ADAM-538] Initial setup.py for pyadam

### PR DESCRIPTION
**Pull request by laserson**
Not for merge at this time.  Just here to track progress.

### CODE REVIEW

**Comment by laserson** [comment]
Ok, after thinking about this a bit, I think it'll be easiest if we work on this bottom up.  What functions do we anticipate needing/wanting in a Python API?  Could people (e.g., @fnothaft @tdanford @massie) comment on what functions/RDD classes they want for their workflows?  I am biased by what I've been interested recently, but I certainly want the ability to do `RegionJoin`s.

**Comment by fnothaft** [comment]
@laserson what is your status on this? Might be a good discussion item for tomorrow's call.

**Comment by laserson** [comment]
Been on the backburner for a bit.  Some eggo stuff is wrapping up so should be able to get to it in the next couple weeks.

**Comment by massie** [comment]
Should we keep this PR open @laserson ?

**Comment by laserson** [comment]
This is definitely on the bac-kburner for me at the moment.  Up to you...

**Comment by fnothaft** [comment]
Closing this for now.

**Pull request closed without merging**
