### PR TITLE
Move non-genomics code

### LINKED ISSUE #475: Remove code that is now in bdg-utils
Now that we've cut the first release of [bdg-utils](https://github.com/bigdatagenomics/bdg-utils/releases/tag/bdg-utils-parent-0.0.1), we should eliminate the non-genomics specific code from this repo, e.g.:

* Parquet
* Metrics
* SparkFunSuite

### PR DESCRIPTION
**Pull request by fnothaft**
This resolves #475 by removing the non-genomics specific code which has been migrated to [bdg-utils](https://www.github.com/bigdatagenomics/bdg-utils), and pointing at bdg-utils where necessary. Specifically, we've moved the:

* SparkFunSuite
* Parquet reimplementation
* Metrics
* Instrumentation

### CODE REVIEW

**Comment by fnothaft** [comment]
I expect this failure because I was building against https://github.com/bigdatagenomics/bdg-utils/pull/19. This will pass once https://github.com/bigdatagenomics/bdg-utils/pull/19 is merged.

**Comment by fnothaft** [comment]
Ta-da! And, this now is working with @nfergu's work from #514 on top, and building against https://github.com/bigdatagenomics/bdg-utils/pull/19. The build _will_ fail here though, since we haven't merged https://github.com/bigdatagenomics/bdg-utils/pull/19 upstream.

**Comment by massie** [comment]
Switching to `SparkFunSuite` in `bdg-utils` will revert the work I did in ADAM to fix all the test bind errors. We need to port that into `bdg-utils`.

**Comment by fnothaft** [comment]
@massie thanks for catching that! I will port that right now.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Once https://github.com/bigdatagenomics/bdg-utils/pull/22 is merged, this will pass.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Now that this _really_ is passing, I've cut a [new bdg-utils release](https://github.com/bigdatagenomics/bdg-utils/releases/tag/bdg-utils-parent-0.1.1). I'll update this PR once that release is present in Maven Central.

**Comment by massie** [comment]
Thanks, Frank!

**Comment by nfergu** [comment]
@fnothaft -- looks great! Just tried the latest version locally and it works well.

Just one comment: I think the Timers object should be in ADAM rather than bdg-utils as it contains ADAM-specific timers. I'll raise separate PRs to move it.

**Comment by fnothaft** [comment]
@nfergu ah, drat! You are indeed correct! I'd created an earlier version that did that correctly ;). Thanks for catching this, and I'll review and merge your two PRs shortly.

**Pull request merged**
