### PR TITLE
[ADAM-549] Added documentation for testing and CI for ADAM.

### LINKED ISSUE #549: Document the testing/CI flow for ADAM
Currently, our docs don't contain much information about how to run tests, or how ADAM's CI system is deployed.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #549. Adds a small bit of documentation about how to run and write unit and integration tests for ADAM, as well as documentation about our CI practices.

### CODE REVIEW

**Comment by fnothaft** [comment]
_Siiiiigh..._

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
Thanks, Frank!

**Pull request merged**
