### PR TITLE
[ADAM-543][ADAM-544] Fix issues with ADAM scripts and classpath

### LINKED ISSUE #543: If a user runs adam-shell with their own --jars, their setting will be clobbered

### LINKED ISSUE #544: adam-pyspark fails to load ADAM classes
Related to [SPARK-5185](https://issues.apache.org/jira/browse/SPARK-5185).  Need to pass the additional classpath settings in `--driver-class-path`

### PR DESCRIPTION
**Pull request by laserson**
Note that this adds a *Python* utility script to `bin/`.  Is this ok?  Parsing the command line in bash just seemed so much less appetizing.  This also has a workaround for SPARK-5185.

Fixes #543.
Fixes #544.

### CODE REVIEW

**Comment by fnothaft** [comment]
I'm OK with python.

**Comment by fnothaft** [comment]
Also, LGTM.

**Comment by laserson** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Merged! Thanks @laserson!

**Pull request merged**
