### PR TITLE
Remove back reference between VariantAnnotation and Variant

### PR DESCRIPTION
**Pull request by heuermh**
Fallout from removing back reference between `VariantAnnotation` and `Variant` as in https://github.com/bigdatagenomics/bdg-formats/pull/117.

The forward reference between `Variant` and `VariantAnnotation` will be developed in https://github.com/bigdatagenomics/adam/pull/1288.

### CODE REVIEW

**Comment by heuermh** [comment]
@fnothaft any clue what this test failure is about?  I've never looked at the flatten-related stuff before.

**Comment by fnothaft** [comment]
@heuermh what do we want the merge sequence to be with this PR? If you've got some time this morning, perhaps we could chat real quick?

**Comment by heuermh** [comment]
> If you've got some time this morning, perhaps we could chat real quick?

Yep, let me know when and where

**Comment by fnothaft** [comment]
>> If you've got some time this morning, perhaps we could chat real quick?
>
> Yep, let me know when and where

Just shot you a bluejeans link to your Gmail. Call on in whenever you're free.

**Comment by fnothaft** [comment]
Cherry-picked over to #1288 as https://github.com/bigdatagenomics/adam/pull/1288/commits/2398aa210e5271616425d36de608aba654ad236f.

**Comment by heuermh** [comment]
Thank you!

**Pull request closed without merging**
