### PR TITLE
[ADAM-709] Remove unused FeatureHierarchy

### PR DESCRIPTION
**Pull request by neurons**
As per the discussion on [issue 709](https://github.com/bigdatagenomics/adam/issues/709), the general consensus seems to be to remove FeatureHierarchy. This commit removes FeatureHierarchy.scala and FeatureHierarchySuite.scala from adam.

### CODE REVIEW

**Comment by neurons** [comment]
Jenkins [console log](https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/766/console) un-informative. Despite the fact that all builds with different hadoop and scala versions show no failures, jenkins indicates build failure. Anyone have an explanation?

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Hi @neurons! Thanks for opening the PR. @AmplabJenkins is reporting the following error across builds:

```
[INFO] /home/jenkins/workspace/ADAM-prb/SCALAVER/2.10/hadoop.version/1.0.4/label/centos/adam-cli/src/main/scala:-1: info: compiling
[INFO] Compiling 23 source files to /home/jenkins/workspace/ADAM-prb/SCALAVER/2.10/hadoop.version/1.0.4/label/centos/adam-cli/target/scala-2.10.4/classes at 1435957054653
[ERROR] /home/jenkins/workspace/ADAM-prb/SCALAVER/2.10/hadoop.version/1.0.4/label/centos/adam-cli/src/main/scala/org/bdgenomics/adam/cli/Features2ADAM.scala:23: error: object BaseFeature is not a member of package org.bdgenomics.adam.models
[ERROR] import org.bdgenomics.adam.models.BaseFeature
[ERROR]        ^
[ERROR] one error found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ADAM_2.10 ......................................... SUCCESS [5.938s]
[INFO] ADAM_2.10: Core ................................... SUCCESS [3:53.280s]
[INFO] ADAM_2.10: APIs for Java .......................... SUCCESS [15.285s]
[INFO] ADAM_2.10: CLI .................................... FAILURE [4.720s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:19.429s
[INFO] Finished at: Fri Jul 03 13:57:39 PDT 2015
[INFO] Final Memory: 47M/1874M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:compile (scala-compile-first) on project adam-cli_2.10: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

Perhaps you have a local update to `adam-cli/src/main/scala/org/bdgenomics/adam/cli/Features2ADAM.scala` that didn't get pushed?

**Comment by fnothaft** [comment]
Hi @neurons! I just wanted to ping and see if you were able to look at the build issue.

**Comment by neurons** [comment]
Sorry about the delay @fnothaft. I was able to see the build failure locally. The problem seems to have been due to the presence of BaseFeature import statement in Features2ADAM.scala. BaseFeature is an object in FeatureHierarcy.scala. Build is now successful locally. Going to do another round of tests before sending in another pull request.

**Comment by fnothaft** [comment]
No problem @neurons! I figured you were busy. You don't need to open a new PR with the changes; you can just push to the branch you opened this PR from originally. Looking forward to it!

**Comment by neurons** [comment]
@fnothaft Unfortunately, due to a variety of issues, I had to make an new [PR](https://github.com/bigdatagenomics/adam/pull/728). Will stick to one PR next time.

**Comment by fnothaft** [comment]
@neurons no problem! Whatever is easiest for you. I'll close this one, in favor of the new one.

**Pull request closed without merging**
