### PR TITLE
[ADAM-1453] Add hooks to publish ADAM docs from CI flow.

### LINKED ISSUE #1453: Publish Markdown and Scaladoc to the interwebs
We used to use https://github.com/bigdatagenomics/adam/blob/master/scripts/publish-scaladoc.sh but it didn't work well.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1453.

### CODE REVIEW

**Comment by fnothaft** [comment]
@heuermh ping me before you merge this, because it will require a small change to @AmplabJenkins. Essentially, we just need to sequence this/the Jenkins change and #1412.

**Comment by heuermh** [comment]
Resolves #774

**Comment by fnothaft** [comment]
@AmplabJenkins is updated; this is good to go from my side.

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Pull request merged**
