### PR TITLE
[ADAM-1886] fix for pyadam to recognize >1 egg file

### PR DESCRIPTION
**Pull request by akmorrow13**

### CODE REVIEW

**Comment by akmorrow13** [comment]
Resolves https://github.com/bigdatagenomics/adam/issues/1886

**Comment by heuermh** [comment]
`find-adam-egg.sh` now matches `find-adam-assembly.sh`

**Comment by fnothaft** [comment]
@heuermh if this is good on your end, please merge

**Comment by heuermh** [comment]
Thank you, @akmorrow13!

**Pull request merged**
