### PR TITLE
[ADAM-1512] Support VCFs with +Inf/-Inf float values.

### LINKED ISSUE #1512: Allow +Inf and -Inf Float values when reading VCF
Per the VCF 4.3 specification,

Float (32-bit, formatted to match the regular expression
`^[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?$`, `NaN`, or `+/-Inf`)

From what I can tell, Scala float parsing delegates to [the implementation in java](https://docs.oracle.com/javase/7/docs/api/java/lang/Double.html#valueOf(java.lang.String)), which uses
```
...
"[+-]?(" + // Optional sign character
"NaN|" +           // "NaN" string
"Infinity|" +      // "Infinity" string
...
```

Thus we may need to special case `+Inf` and `-Inf`.  Reported by @tangxuan_twitter on [Gitter](https://gitter.im/bigdatagenomics/adam).

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1512. @heuermh do you have any VCFs that reproduce this issue? It would be good to add a test resource, if we've got one.

### CODE REVIEW

**Comment by heuermh** [comment]
> @heuermh do you have any VCFs that reproduce this issue? It would be good to add a test resource, if we've got one.

I do not, it was reported on gitter.
https://gitter.im/bigdatagenomics/adam?at=59b9a77ec101bc4e3ac33d56

**Comment by heuermh** [comment]
I hacked up `sorted.vcf` as a test file and am still seeing
```
2017-09-26 12:01:01 WARN  VariantContextConverter:361 - Caught exception
java.lang.NumberFormatException: For input string: "-Inf" when converting
[VC Unknown @ 1:14397-14400 Q. of type=INDEL alleles=[CTGT*, C]
attr={AC=2, AF=+Inf, AN=6, BaseQRankSum=-Inf, ClippingRankSum=0.138,
DP=69, FS=7.786, MLEAC=2, MLEAF=0.333, MQ=26.84, MQ0=0, MQRankSum=-1.906,
QD=1.55, ReadPosRankSum=0.384} GT=[[NA12878 CTGT*/C GQ 99 DP 20 AD 16,4
PL 120,0,827 FT rd {MQ=-Inf, PQ=+Inf}],[NA12891 CTGT*/C GQ 60 DP 10 AD 8,2
PL 60,0,414 FT dp;rd],[NA12892 CTGT*/CTGT* GQ 99 DP 39 AD 39,0
PL 0,116,2114]].
- support VCFs with +Inf/-Inf float values *** FAILED ***
...
```

**Comment by heuermh** [comment]
Created pull request https://github.com/fnothaft/adam/pull/20 with additional fixes and test file.

**Comment by heuermh** [comment]
Did I mess up with git or maybe is github confused?  What happened to commit e20c32c1e6647b48d39470a86582efa1c6716dc1?

**Comment by fnothaft** [comment]
@heuermh no, I think that was my screwup. Let me fix that up...

**Comment by fnothaft** [comment]
@heuermh fixed; sorry about that, I'd dropped it during the rebase.

**Comment by heuermh** [comment]
Sorry, that commit needs ```vcs.toVariantRDD()``` &rarr; ```vcs.toVariants()```
and ```vcs.toGenotypeRDD()``` &rarr; ```vcs.toGenotypes()```

```
...
[INFO] /home/jenkins/workspace/ADAM-prb/HADOOP_VERSION/2.6.2/SCALAVER/2.10/SPARK_VERSION/1.6.3/label/centos/adam-core/src/test/scala:-1: info: compiling
[INFO] Compiling 88 source files to /home/jenkins/workspace/ADAM-prb/HADOOP_VERSION/2.6.2/SCALAVER/2.10/SPARK_VERSION/1.6.3/label/centos/adam-core/target/2.10.6/test-classes at 1507524292274
[ERROR] /home/jenkins/workspace/ADAM-prb/HADOOP_VERSION/2.6.2/SCALAVER/2.10/SPARK_VERSION/1.6.3/label/centos/adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala:167: error: value toVariantRDD is not a member of org.bdgenomics.adam.rdd.variant.VariantContextRDD
[ERROR]     val variant = vcs.toVariantRDD().rdd.filter(_.getStart == 14396L).first()
[ERROR]                       ^
[ERROR] /home/jenkins/workspace/ADAM-prb/HADOOP_VERSION/2.6.2/SCALAVER/2.10/SPARK_VERSION/1.6.3/label/centos/adam-core/src/test/scala/org/bdgenomics/adam/rdd/variant/VariantContextRDDSuite.scala:172: error: value toGenotypeRDD is not a member of org.bdgenomics.adam.rdd.variant.VariantContextRDD
[ERROR]     val genotype = vcs.toGenotypeRDD().rdd.filter(_.getVariant == variant).first()
[ERROR]                        ^
[ERROR] two errors found
```

**Comment by fnothaft** [comment]
@heuermh yeah, I'd just patched that after the last failure. Let's see what this new failure is.

**Comment by fnothaft** [comment]
Need to update a unit test; will get that in a sec.

**Comment by heuermh** [comment]
Yup that glob count one is hard to keep in sync when rebasing

**Comment by fnothaft** [comment]
Yup, should be updated now.

**Comment by heuermh** [comment]
Merged as commit ca36dd6.  Thank you, @fnothaft

**Pull request merged**
