### PR TITLE
[ADAM-595] Delete the 'comparisons' code.

### LINKED ISSUE #595: Move the 'comparisons' code into a separate repository.
As part of our attempt to slim down the core ``adam`` module into its minimal set of classes, and also as preparation for re-writing some of the Picard-style metrics (this is relevant to the NCI Cloud Pilot project), we should move out all the core code and commands which compute read- and variant-level metrics from the adam-core module into a separate module and repository. 

This repository (qc-metrics) has already been created.  This issue is for deleting the code (in org.bdgenomics.adam.metrics), the ComparisonTraversalEngine class, all their test suites, and the two commands (FindReads and CompareADAM) which depend on them.  

All of this will be re-created in the qc-metrics repository.

### PR DESCRIPTION
**Pull request by tdanford**
This means deleting the comparisons code here; these files (Comparisons,
AvailableComparisons, and GeneratorFilter) are moving into the qc-metrics
package, along with the ComparisonsTraversalEngine.

Also being deleted are the test-suites for each of these classes.

Finally, the CLI commands which use these classes, CompareADAM and
FindReads, are also being deleted.

Each of these classes will be moved into the qc-metrics repository as
part of a separate pull request.

This resolves #595

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by tdanford** [comment]
If this builds, Frank, I think it's ready to go.

**Comment by fnothaft** [comment]
Let's cut it loose! Thanks @tdanford!

**Comment by tdanford** [comment]
Thanks @fnothaft.

**Pull request merged**
