### PR TITLE
fixed an issue where bytes corresponding to read name were being counted twice

### PR DESCRIPTION
**Pull request by agarg2008**
Issue : In 'SingleFastqInputFormat' class, bytes length corresponding to readname is skipped twice.
Impact : Recordreader will not read all the records. Records towards the end will be skipped because of range check (pos>=end) in next method.

Fix : Removed the redundant increment.

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, add to whitelist and test this please.

**Comment by massie** [comment]
This looks good to me. What do you think, @fnothaft ?

**Comment by fnothaft** [comment]
+1, let's rebase and merge

**Comment by agarg2008** [comment]
Synced with latest BDG master branch.

**Comment by fnothaft** [comment]
Thanks @agarg2008! I've manually merged this as https://github.com/bigdatagenomics/adam/commit/3be1fb041e87ddeb6aa2eee0e0516370310b612f.

**Pull request closed without merging**
