### PR TITLE
[ADAM-597] Move correction out of ADAM and into a downstream project.

### LINKED ISSUE #597: Migrate correction package into a downstream repository
I've created a downstream repository ([corretto](https://github.com/bigdatagenomics/corretto)) for read error correction based utils. We should move the `org.bdgenomics.adam.rdd.read.correction` package there.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #597. Removes correction code from ADAM. I will add this to [corretto](https://github.com/bigdatagenomics/corretto).

### CODE REVIEW

**Comment by laserson** [comment]
ready to merge?

**Comment by fnothaft** [comment]
Let me rebase.

**Comment by fnothaft** [comment]
Rebased.

**Comment by laserson** [comment]
Merged.  Thanks @fnothaft!

**Pull request merged**
