### PR TITLE
Remove Gene and related models and parsing code

### LINKED ISSUE #1129: Remove Gene and related models and parsing code
In addition to the changes proposed in #1118, remove Gene and related models and remove the parsing code in FeatureParser.

This could be added to the pull request linked above or split out into a separate pull request.

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1129

### CODE REVIEW

**Comment by heuermh** [comment]
Note the Spark 2.0 Jenkins tests won't pass until https://github.com/bigdatagenomics/utils/issues/80 and #1123 are in.

**Comment by fnothaft** [comment]
+1

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by fnothaft** [comment]
Thanks @heuermh! I've merged this as https://github.com/bigdatagenomics/adam/commit/9eb0d60fe41dcdf99b7025d794032040fd9a8edc.

**Comment by heuermh** [comment]
Thanks!

**Pull request closed without merging**
