### PR TITLE
RangeFetch Implemented

### PR DESCRIPTION
**Pull request by bkthayillam**
Implemented a RangeFetch that will print out the specified range from specified chromosome from adam format file.

### CODE REVIEW

**Comment by fnothaft** [comment]
@bkthayillam I'm not sure if you meant to close this, but I'm going to reopen it and run the tests.

**Comment by fnothaft** [comment]
Jenkins, add to whitelist.

**Comment by fnothaft** [comment]
Jenkins, add to whitelist.

**Comment by fnothaft** [comment]
Can you run `scripts/format-sources`? Otherwise, this PR passes the tests.

**Comment by bkthayillam** [comment]
Sorry for any trouble but I submitted this pull request by mistake while trying to pull request to my own forked master. If it works, feel free to merge it but currently I'm waiting on my mentor to know what I was supposed to do with this edit.

**Comment by fnothaft** [comment]
@bkthayillam no trouble at all! We can just keep it open for the time being.

**Pull request closed without merging**
