### PR TITLE
Add test sample(verify  number of reads in loadAlignments function)  and ADAM SNAPSHOT document

### PR DESCRIPTION
**Pull request by xubo245**
add test sample : sc.loadAlignments should not fail on single-end and paired-end fastq reads

there are some problem in adam-0.21.0, link: https://github.com/bigdatagenomics/adam/issues/1424

It was fixed in Adam-0.21.1-SNAPSHOT, link  https://github.com/bigdatagenomics/adam/commit/0e5735756dccd41a1aeac922c11b2463db697e7f;  So I only add a test sample for it!

### CODE REVIEW

**Comment by xubo245** [comment]
I test the native data in adam-0.21.0. the number of line in bqsr1-r1.fq is 1952, it should be 488 reads.
bqsr1-r2.fq too.

It should be total 976 reads after loadAlignments, but there are 892 reads by running my code.

code:

  sparkTest("load fastq") {
    val fastq1Path = testFile("bqsr1-r1.fq")
    val fastq2Path = testFile("bqsr1-r2.fq")
    var align1=sc.loadAlignments(fastq1Path,filePath2Opt = Option(fastq2Path))
    println(align1.rdd.count())
    println(align1.rdd.count()*2)
  }
I add the code into org.bdgenomics.adam.cli.Adam2FastqSuite
the data in adam-adam-parent-spark2_2.10-0.21.0\adam-cli\src\test\resources

result:

2017-03-08 11:21:46 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-03-08 11:21:47 WARN  MetricsSystem:71 - Using default name DAGScheduler for source because spark.app.id is not set.
892
1784

=>
892!=976

**Comment by xubo245** [comment]
some related issue: 
https://github.com/bigdatagenomics/adam/issues/1428

https://github.com/bigdatagenomics/adam/issues/1432

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by xubo245** [comment]
I can not find any error from my code  in https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/HADOOP_VERSION=2.3.0,SCALAVER=2.11,SPARK_VERSION=1.6.1,label=centos/1850/consoleText,  the errors are other functions'...

Can you tell me where error in my PR code?

**Comment by fnothaft** [comment]
Hi @xubo245! Apologies for the slow reply, been busy the last few days tracking down various bugs and etc. None of the tests failed, but our source formatting check failed. Can you run `./scripts/format-source` from the root of your local checkout, commit the changes, and push to your PR branch? This should fix the formatting issues. Let me know if you have any issues otherwise! Otherwise, this test looks good to me, thanks for adding it!

**Comment by xubo245** [comment]
Don‘t worry.
What are  various bugs in your track? Can you tell me?please. 

I run in another branch: https://github.com/bigdatagenomics/adam/pull/1434#issuecomment-286334435’
It is the same as this.

Thanks you very much!

**Comment by fnothaft** [comment]
> What are various bugs in your track? Can you tell me?please.

Definitely! I'm most focused on finishing up #1423 and #1412 right now.

**Comment by xubo245** [comment]
Thanks， I also need to invoke BQSR 、MarkDuplicates and SNP/INDEL discovery function to process  adam data later. May I ask you some questions if I have problem about it later?

**Comment by heuermh** [comment]
Succeeded by #1448.

**Comment by xubo245** [comment]
I raise a PR, but why don't you review this PR and then merge it ? but raise https://github.com/bigdatagenomics/adam/pull/1448/files,.............

**Pull request closed without merging**
