### PR TITLE
[ADAM-1225] Move helper functions from ADAMFunSuite to SparkFunSuite.

### LINKED ISSUE #1225: Move ADAMFunSuite helper functions upstream to SparkFunSuite
I'm finding use for some of the functions (`tmpFile`, `resourceUrl`) in downstream projects. Would anyone be against moving these to `org.bdgenomics.utils.misc.SparkFunSuite`?

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1225. Depends on https://github.com/bigdatagenomics/utils/pull/89 and a bdg-utils 0.2.9 release.

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
OK, this is good to go other than the build issues caused by #1221/#1254.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Thank you, @fnothaft!  And thanks for cutting the bdg-utils 0.2.9 release as well.

**Pull request merged**
