### PR TITLE
[ADAM-1999] Support Python 3

### LINKED ISSUE #1999: Support Python 3
I believe this is actually entirely a build thing. I'll investigate this more and report exact steps that need to be complete.

### PR DESCRIPTION
**Pull request by akmorrow13**
Fixes #1999

### CODE REVIEW

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
@heuermh  ping for review

**Comment by akmorrow13** [comment]
@heuermh rebased

**Comment by heuermh** [comment]
Thank you, @akmorrow13

**Pull request merged**
