### PR TITLE
[ADAM-1170] Deprecate SAMFileHeaderWritable

### LINKED ISSUE #1170: Clean up packaging of conversion methods
Continued from #1157. We should:
- Do a review pass and make some of the `AlignmentRecordConverter` methods private
- Make `SAMFileHeaderWritable` private to ADAM, and change the `AlignmentRecordConverter.convert` signature to take a `SAMFileHeader`

Also, contributed for discussion by @heuermh:

> > Also, I think it's more useful to have the conversion utility at the record level, rather than the RDD level, since then it can be used outside Spark.
> 
> If that were the case, it would be preferable to me to have the conversion stuff written in Java instead of Scala and be a library external to ADAM.

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1170

### CODE REVIEW

**Comment by akmorrow13** [comment]
Some local benchmarks
------------------------
800MB bam file:
OLD:
```
real	2m13.281s
user	11m40.431s
sys	0m10.263s
```
NEW:
```
real	2m5.253s
user	11m16.020s
sys	0m10.250s
```

3.6GB SAM file 
OLD
```
real	2m7.400s
user	11m56.519s
sys	0m15.019s
```

NEW
```
real	0m2.623s
user	0m5.010s
sys	0m0.484s
```

**Comment by heuermh** [comment]
What, did that last run terminate early or something?

**Comment by akmorrow13** [comment]
Fixed

**Comment by heuermh** [comment]
Thanks, that looks better.  I only expect to see differences (if any) across multi-node clusters, because this pull request changes how the headers are serialized.

Unfortunately, this https://github.com/bigdatagenomics/adam/issues/2157 prevents running on 2.2.x on the bdg cluster, and we don't have Spark 2.4.x available there yet.

**Comment by heuermh** [comment]
Here are some results running on (rather undersized) m3.xlarge instances in AWS EMR for 5.7G BAM file on HDFS

git HEAD
```
$ time ./bin/adam-submit \
  --master yarn \
  --deploy-mode cluster \
  --driver-memory 8g \
  --executor-memory 8g \
  --conf spark.driver.cores=6 \
  --conf spark.executor.cores=6 \
  --conf spark.executor.memoryOverhead=2048 \
  -- \
  transformAlignments \
  NA12878.chrom22.CGI.teramap.CEU.high_coverage.20120417.bam \
  NA12878.chrom22.CGI.teramap.CEU.high_coverage.20120417.alignments.adam

(3 nodes + driver)

real	12m56.854s
user	0m17.041s
sys	0m2.501s

(4 nodes + driver)

real	9m32.446s
user	0m16.184s
sys	0m2.372s
```

#2156 heuermh:prepare-for-convert branch
```
$ time ./bin/adam-submit \
  --master yarn \
  --deploy-mode cluster \
  --driver-memory 8g \
  --executor-memory 8g \
  --conf spark.driver.cores=6 \
  --conf spark.executor.cores=6 \
  --conf spark.executor.memoryOverhead=2048 \
  -- \
  transformAlignments \
  NA12878.chrom22.CGI.teramap.CEU.high_coverage.20120417.bam \
  NA12878.chrom22.CGI.teramap.CEU.high_coverage.20120417.2156.alignments.adam

(3 nodes + driver)

real	13m29.480s
user	0m16.762s
sys	0m2.591s

(4 nodes + driver)

real	9m36.646s
user	0m16.260s
sys	0m2.218s
```

**Pull request merged**
