### PR TITLE
fix bash arg array processing in adam-submit

### LINKED ISSUE #971: Arg-array parsing problem in adam-submit
spark args with spaces in them are not handled properly:
```
$ bin/adam-submit --conf "spark.driver.extraJavaOptions=-XX:+PrintGCDetails -XX:+PrintGCTimeStamps -verbose:gc" -- flagstat adam-core/src/test/resources/small.sam
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/Users/ryan/sparks/spark-1.6.0-bin-hadoop2.6/bin/spark-submit
Error: Unrecognized option: -XX:+PrintGCTimeStamps

Usage: spark-submit [options] <app jar | python file> [app arguments]
Usage: spark-submit --kill [submission ID] --master [spark://...]
Usage: spark-submit --status [submission ID] --master [spark://...]

Options:
…
```
PR incoming imminently

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #971

### CODE REVIEW

**Comment by heuermh** [comment]
LGTM, thank you!

**Comment by heuermh** [comment]
Merged in commit 5d3cdb74ccb5bc277af545fbf4170e36b2acf530

**Comment by heuermh** [comment]
Hmm.  Now why does it say "This pull request is closed, but the args branch has unmerged commits."?

I'm using ```scripts/commit-pr.sh``` and sometimes it seems to do the right thing and sometimes not.

**Comment by fnothaft** [comment]
Did the commit get rebased by the `commit-pr.sh` script? If so, the git commit hash changes and Github shows the "unmerged commits" message.

**Comment by heuermh** [comment]
Not sure.  Closing in on the limits of my git knowledge.

```bash
$ ./scripts/commit-pr.sh 972
Current branch master is up to date.
From https://github.com/bigdatagenomics/adam
 * [new ref]         refs/pull/972/head -> pr-972
Switched to branch 'pr-972'
First, rewinding head to replay your work on top of it...
Applying: fix bash arg array processing in adam-submit
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Updating a505bb9..5d3cdb7
Fast-forward
 bin/adam-submit | 12 ++++++------
 1 file changed, 6 insertions(+), 6 deletions(-)
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 557 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 1 (delta 0)
To https://github.com/bigdatagenomics/adam.git
   a505bb9..5d3cdb7  master -> master
```

**Comment by fnothaft** [comment]
This line:

```
First, rewinding head to replay your work on top of it...
```

is the rebase occuring.

**Pull request closed without merging**
