### PR TITLE
[ADAM-2262] Update Spark dependency version to 2.4.6

### LINKED ISSUE #2262: Update Spark dependency version to 2.4.6

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #2262

### CODE REVIEW

**Comment by heuermh** [comment]
Hello @shaneknapp, I thought perhaps the issue with the first Jenkins test failure above might have been insecure `http` access, but that appears not to be the case.  Are there some other network restrictions in place?

```
+ curl \
-L https://www-us.apache.org/dist/hadoop/common/hadoop-2.7.7/hadoop-2.7.7.tar.gz \
-o hadoop-2.7.7.tar.gz
...
curl: (7) Failed to connect to downloads.apache.org port 443: Connection timed out
```
https://amplab.cs.berkeley.edu/jenkins/job/ADAM-prb/3099/HADOOP_VERSION=2.7.5,SCALAVER=2.12,SPARK_VERSION=2.4.5,label=ubuntu/console

**Comment by shaneknapp** [comment]
sigh.  i wonder if we were blacklisted again.

**Comment by heuermh** [comment]
Ah, perhaps I can rework it to use the `https://www.apache.org/dyn` mirror instead . . . will try shortly

**Comment by shaneknapp** [comment]
yeah, try that...  but if we're blacklisted, that means that something
isn't cached locally that should be.  i don't think it's this build that's
broken, but you're just seeing the impact.

this has happened before...  :)

just opened an apache infra jira to help me figure it out:
https://issues.apache.org/jira/browse/INFRA-20463

**Comment by shaneknapp** [comment]
word.

using the mirror is the best bet, and apache infra found a few servers that
still had us blacklisted and fixed that as well.

we should be g2g.

**Comment by heuermh** [comment]
Awesome!  Thank you for your help, @shaneknapp, as always.

**Pull request merged**
