### PR TITLE
Removes the predicates package.

### PR DESCRIPTION
**Pull request by fnothaft**
Follow on cleanup to #609. We shouldn't need the predicates package after migrating to `filter2` and removing the automagical predicates.

### CODE REVIEW

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Also, in #609 `parquet-scala` was added with scope `test`. I've removed the `test` scoping so that it is provided in the adam-shell.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by laserson** [comment]
I love all this deletion!  Any reason to wait before merge?

**Comment by massie** [comment]
None, Uri. Feel free to push the button. :)


-Matt

**Comment by laserson** [comment]
lol, done! https://www.youtube.com/watch?v=ctAymN-ff6c&t=1m57s

**Comment by fnothaft** [comment]
> I love all this deletion!

+1!

**Pull request merged**
