### PR TITLE
Support Apache Spark 3.x in build

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
force pushing #ftl

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
i'm assuming that the earlier failure was spurious and i'm both unable to reproduce it, and the builds are showing that the proper certs are being used.

¯\\_(ツ)_/¯

**Comment by heuermh** [comment]
That is good to hear.  I also had an unrelated code signing key failure this afternoon, maybe there are some bad vapours in the clouds today.

**Comment by shaneknapp** [comment]
> That is good to hear. I also had an unrelated code signing key failure this afternoon, maybe there are some bad vapours in the clouds today.

sunspots maybe?  ;)

**Comment by karenfeng** [comment]
Hi @heuermh, I tried this out on a cluster and ran into some issues inside the initialization of [`GenomicDataset`](https://github.com/bigdatagenomics/adam/pull/2255/files#diff-4f9d88471a8d1a9a20e72781f9a0c0ccR131).
```
Caused by: org.apache.spark.SparkException: A master URL must be set in your configuration
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:437)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2811)
	at org.apache.spark.sql.SparkSession$Builder.$anonfun$getOrCreate$5(SparkSession.scala:1001)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:992)
	at org.bdgenomics.adam.rdd.GenomicDataset.$init$(GenomicDataset.scala:131)
	at org.bdgenomics.adam.rdd.AvroGenomicDataset.<init>(GenomicDataset.scala:3762)
	at org.bdgenomics.adam.rdd.AvroReadGroupGenomicDataset.<init>(GenomicDataset.scala:3407)
	at org.bdgenomics.adam.rdd.read.AlignmentDataset.<init>(AlignmentDataset.scala:399)
	... 74 more
```
The relevant line looks like this:
```
@transient val spark = SparkSession.builder().getOrCreate()
```
If I made `spark` a `lazy val` like so...
```
@transient lazy val spark = SparkSession.builder().getOrCreate()
```
... the problem went away. It probably wouldn't hurt to make the parallel `spark` in [`ADAMContext`](https://github.com/bigdatagenomics/adam/pull/2255/files#diff-d36ea7d0742decd0b040a73a96af06e9R1596) a `lazy val` as well.

**Comment by heuermh** [comment]
Thank you, @karenfeng!  Those changes worked ok for me locally, I pushed another commit

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
Jenkins, retest this please

**Comment by heuermh** [comment]
```
> library(devtools);devtools::document()
Updating bdgenomics.adam documentation
Loading bdgenomics.adam
Error in (function (dep_name, dep_ver = NA, dep_compare = NA)  : 
  Dependency package SparkR not available.
```

**Comment by heuermh** [comment]
Jenkins, retest this please

**Pull request merged**
