### PR TITLE
feat: speed up 2bit file extract

### PR DESCRIPTION
**Pull request by Blaok**
Rewrite the extract logic.
On a single node with 20 workers, BaseRecalibration time is reduced from 5.8 min to 1.7 min.
Pass existing tests.

### CODE REVIEW

**Comment by fnothaft** [comment]
Wonderful! Thank you for submitting the patch; I will take a look at this later today or tomorrow.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Is there an ε we can provide to coveralls to prevent it from failing a build in silly cases like this one?  Coverage decreased by 0.003%?  Come on.

**Comment by fnothaft** [comment]
@laserson would you be able to review this today or tomorrow, since you wrote the original 2bit code? If not, I think this is good to go and I will merge as is.

**Comment by fnothaft** [comment]
Merged! Thanks @Blaok for the contribution! We greatly appreciate it.

**Pull request merged**
