### PR TITLE
[ADAM-1361] Fix misnamed ADAM überjar.

### LINKED ISSUE #1361: Assembly final name doesn't include spark2 for Spark 2.x builds
The Spark 2.x builds produce assembly artifacts without spark2 in their name
```xml
<finalName>adam_${scala.version.prefix}-${project.version}</finalName>
```

After a change `adam-submit` and `adam-shell` may need to be updated.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1361.

### CODE REVIEW

**Comment by heuermh** [comment]
With this
```
diff --git a/scripts/move_to_spark_2.sh b/scripts/move_to_spark_2.sh
index ebd9fd89..3e83ebdd 100755
--- a/scripts/move_to_spark_2.sh
+++ b/scripts/move_to_spark_2.sh
@@ -19,5 +19,6 @@ find . -name "pom.xml" -exec sed \
     -e "/adam-/ s/_2\.1/-spark2_2.1/g" \
     -e "/utils-/ $substitution_cmd" \
     -e "/adam-/ $substitution_cmd" \
+    -e "/adam_/ $substitution_cmd" \
     -e "/spark.version/ s/1.6.3/2.1.0/g" \
     -i.spark2.bak '{}' \;
```
the `<finalName>` element can stay as is.  This PR adds `-assembly` to the assembly artifact names.

**Comment by fnothaft** [comment]
@heuermh Since the assembly jars are largely handled programmatically from the `./bin/adam-*` scripts, I don't really see a benefit to changing the JAR name with `<finalName>`. I'd rather eliminate `<finalName>` and have one fewer place where things can go wrong in the `move_to` scripts.

**Comment by heuermh** [comment]
I don't feel strongly either way.

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Pull request merged**
