### PR TITLE
[ADAM-962] Fix corrupt single-file BAM output.

### LINKED ISSUE #962: BAM output in ADAM appears to be corrupt
Crosslinking to https://github.com/BD2KGenomics/toil-scripts/issues/117.

### PR DESCRIPTION
**Pull request by fnothaft**
It seems like we were doing something incorrectly when writing the header. Additionally, we now write a correct end-of-file. Resolves #962.

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
This worked for me in at least one instance.

Is this just waiting on fixing unit test failures?  I would guess there is simply a problem with ```AlignmentRecordRDDFunctionsSuite.checkFiles``` not handling binary file encoding correctly.  I can look into that.

**Comment by fnothaft** [comment]
> Is this just waiting on fixing unit test failures? I would guess there is simply a problem with AlignmentRecordRDDFunctionsSuite.checkFiles not handling binary file encoding correctly. I can look into that.

IIRC, this was waiting on https://github.com/HadoopGenomics/Hadoop-BAM/pull/80, but honestly, I'm a bit foggy.

**Comment by heuermh** [comment]
In a branch with this PR applied and Hadoop-BAM at version 7.4.1-SNAPSHOT (including the PR linked above), I still see similar test failures.

**Comment by fnothaft** [comment]
Ah, OK, that confirms that I am remembering wrong... If you wouldn't mind looking into `checkFiles`, I'd be appreciative.

**Comment by heuermh** [comment]
Could you rebase and push this?  I'd like to confirm that there are still issues with Hadoop-BAM version 7.5.0 before changing `checkFiles`.

**Comment by fnothaft** [comment]
This is good to go!

**Comment by heuermh** [comment]
Some thought to ordering between this and #1060 may be necessary, since the latter bumps Hadoop-BAM to 7.6.0.  I propose merging this first and then dealing with any 7.6.0-related changes in behaviour separately.

**Comment by fnothaft** [comment]
I don't think Hadoop-BAM 7.6.0 will impact this patch, but I am OK with merging this before #1060.

**Comment by fnothaft** [comment]
Rebased!

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
