### PR TITLE
Update for bdg-formats code style changes

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM! Can you resolve the conflicts?

**Comment by heuermh** [comment]
Don't see why there would be any.

**Comment by heuermh** [comment]
Oh wait, there's a commit on the feature branch I didn't see before, d86f258db417104d48fb1272db60ea8b8d33f6f1.  That won't work since bdg-formats HEAD builds as 0.9.1-SNAPSHOT.

**Comment by heuermh** [comment]
GIt can't seem to infer what I want to do when I use commands incorrectly
```bash
$ git rebase -i upstream/upgrade-to-bdg-formats-0.10.0
fatal: Needed a single revision
invalid upstream upstream/upgrade-to-bdg-formats-0.10.0
```

**Comment by heuermh** [comment]
That means I'm git stuck.  😦  Please advise.

**Comment by fnothaft** [comment]
Did you do `git fetch upstream`? What happens if you do `git checkout upstream/upgrade-to-bdg-formats-0.10.0`?

**Comment by heuermh** [comment]
Nope.  Not realizing there were any commits on upgrade-to-bdg-formats-0.10.0 I branched from master.

**Comment by heuermh** [comment]
Jenkins isn't getting the latest bdg-formats snapshot build.  Do I have to mvn deploy a snapshot manually or is Jenkins supposed to be taking care of that automatically?

**Comment by fnothaft** [comment]
> Jenkins isn't getting the latest bdg-formats snapshot build. Do I have to mvn deploy a snapshot manually or is Jenkins supposed to be taking care of that automatically?

Jenkins _did_ get the latest bdg-formats snapshot. However! What Jenkins did not do, was build and deploy the snapshot after the last bdg-formats commit was pushed. There was an issue with the refspec for the bdg-formats master branch that caused the git polling hook to fail. The polling hook should run in 10 minutes; I'll trigger this build once Jenkins has pushed the bdg-formats snapshot.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Thanks.  I'm not sure how to interpret the latest build matrix -- only some of the Jenkins build configurations got the right snapshot version?

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Woot!

**Comment by jpdna** [comment]
LGTM - is this ready to merge?

**Comment by fnothaft** [comment]
LGTM

**Comment by heuermh** [comment]
> is this ready to merge?

Yes, please

**Comment by fnothaft** [comment]
Thanks @heuermh! For these PRs against the topic branch, I'm just going to use the green merge button, since we'll eventually need to sort out the topic branch itself.

**Comment by heuermh** [comment]
Thanks!

**Comment by heuermh** [comment]
As far as topic branching goes, should I be merging commits from master here or will we resolve all of those when merging the topic branch?

**Comment by fnothaft** [comment]
I'm thinking that we should periodically rebase the 0.10.0 branch on master. To make it easier to tell when we've got a merge conflict, perhaps we should PR 0.10.0 against master? This way, we'll get a CI build whenever we push an update, and GitHub will tell us whenever we're out of date.

**Comment by fnothaft** [comment]
Opened #1135.

**Pull request merged**
