### PR TITLE
[ADAM-602] Remove plugin code.

### LINKED ISSUE #602: Remove and generalize plugin code
CCing @tdanford @heuermh for comments here.

I would like to strip the plugin code out of ADAM, and move it to a downstream repository, where we'd generalize it a bit further. Specifically, I'd like to have better support for injecting arguments, I'd like to allow plugins to be able to take more than 1 input RDD (e.g., for BQSR and INDEL realignment, where we'd want `RDD[AlignmentRecord], RDD[Variant] => RDD[AlignmentRecord]`), and I'd like to be able to string multiple plugin stages together into a pipeline.

This would also allow us to strip the cruddy "workflow" engine out of avocado.

I've got a few ideas for this that I'm playing around with. I'll ping here once those are a bit further along.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #602:

* Removed the `org.bdgenomics.adam.plugins` package.
* Removed the `PluginExecutor` command.
* Removed the `JavaADAMPlugin` from the Java API.

Not so much a documentation update, but `org.bdgenomics.adam.plugins` was next on my documentation push, and I thought we had a ticket to remove it. CC @heuermh @tdanford because I can't remember if we had a consensus RE: removing plugins or not.

### CODE REVIEW

**Comment by heuermh** [comment]
Some relevant discussion issue in https://github.com/bigdatagenomics/adam/issues/602.  I'm still +1 to the general idea.

**Comment by heuermh** [comment]
Merged commit e545d1ac9b8f4758d706c0ea072415eb458a070a

Thank you, @fnothaft!

**Comment by tdanford** [comment]
Retroactive +1.

**Comment by heuermh** [comment]
Thanks, @tdanford!  Sorry about being overly productive today :)

**Pull request closed without merging**
