### PR TITLE
Merge VariantAnnotation and DatabaseVariantAnnotation records

### PR DESCRIPTION
**Pull request by heuermh**
Work in progress.  Depends on https://github.com/bigdatagenomics/bdg-formats/pull/105.

It appears our test coverage for `DatabaseVariantAnnotation` and related was insufficient, because this pull request passes all unit tests without any changes to `VariantAnnotationConverter`.

Still left to do:
- [ ] Update `VariantAnnotationConverter` for new schema fields
- [ ] Merge code from `VariantAnnotations` into `VariantAnnotationConverter`
- [ ] Code cleanup/refactoring in `VariantContextConverter`, `VariantAnnotationConverter`
- [ ] Write new unit tests where coverage was lacking

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
@heuermh can you rebase?

**Comment by akmorrow13** [comment]
I am getting an error trying to use this with 1000 genomes vcf:

An exception or error caused a run to abort: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat 
java.lang.IllegalAccessError: tried to access method com.google.common.base.Stopwatch.<init>()V from class org.apache.hadoop.mapreduce.lib.input.FileInputFormat

What files does this currently work on?

**Comment by fnothaft** [comment]
Wow, that's an unusual error. By any chance, is there a full stack trace buried in the logs? From the message you've posted, I'm guessing there's a Guava version mismatch that's tripping things up. Is this on the cluster?

**Comment by akmorrow13** [comment]
So it looks like I may have been mistaken. There looks to be issues with the way that VariantContextConverter works. I cannot tell if this is a vcf versioning error or issues in VariantContextConverter. I will play around with it and see what I find.

**Comment by heuermh** [comment]
Using this branch as-is is not very useful, the branch point `upgrade-to-bdg-formats-0.10.0` needs a rebase and then git issues in this branch need to be resolved.  I have other work locally that is blocked on me getting git-unstuck.

**Comment by akmorrow13** [comment]
As this is a blocker from my end, I would like to aid in getting these issues resolved. I am going to continue getting this branch to work from my end. If there is a more recent version please let me know.

**Comment by heuermh** [comment]
Perhaps setting up a time to join up on slack or irc would be most productive.  This Wed afternoon and all day Thu and Fri are good for me.

**Comment by akmorrow13** [comment]
Great. Let's discuss at tomorrow's meeting.

**Comment by heuermh** [comment]
Superceded by #1250

**Comment by fnothaft** [comment]
Closing in favor of #1250.

**Pull request closed without merging**
