### PR TITLE
[ADAM-1551] Emit non-reference model genotype at called sites.

### LINKED ISSUE #1551: Export to VCF does not include symbolic non-ref if site has a called alt
If you call a variant at a site and also have non-reference model (`<NON_REF>`) likelihoods, we should emit that symbolic non-ref allele (along with the likelihoods). The current export code doesn't do this properly.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1551. WIP. Still needs tests.

### CODE REVIEW

**Comment by fnothaft** [comment]
Pinging for review.

**Comment by fnothaft** [comment]
We'll need to cut a bdg-formats release if this does look good to go.

**Comment by fnothaft** [comment]
Thanks @heuermh for the review. I will cut bdg-formats 0.11.1 right now.

**Comment by fnothaft** [comment]
This is ready to go from my side.

**Comment by heuermh** [comment]
Thank you, @fnothaft

**Pull request merged**
