### PR TITLE
[ADAM-589] Removed pileup code.

### LINKED ISSUE #589: Remove pileup code
This code isn't used any more due to poor performance.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #589.

### CODE REVIEW

**Comment by tdanford** [comment]
This code has been a crufty thorn in our side for a long time.  I'm ready to merge this right now.  

Any objections?  Going once... going twice...

**Comment by tdanford** [comment]
Alright, here we go.

**Comment by pkaleta** [comment]
@tdanford I'm trying to follow this tutorial: http://ampcamp.berkeley.edu/5/exercises/genome-analysis-with-adam.html

It's using `adamRecords2Pileup` method which was removed as part of this. Are there any examples/tutorial of how to achieve a similar functionality?

**Comment by fnothaft** [comment]
Hi @pkaleta! We've eliminated this code a long time back. What sort of computation are you trying to run? If you can give details, then we can point you in the direction of the current "best practice".

**Pull request merged**
