### PR TITLE
[ADAM-553] Unify contexts

### LINKED ISSUE #553: Simplify `ADAMContext`
I am finding `ADAMContext` to be more complicated than I'd like, especially when I am thinking about the Python API and the `JavaADAMContext`.  Here are a few questions:

* What is the purpose of `adamLoad`?  We only have a relatively small number of types.  Does it make sense to break `adamLoad` out to the non-generic cases we are interested in?  We already have a `loadAlignments` function.

* What is the purpose of `adamDictionaryLoad`?  It looks like it's basically an agg on an `RDD[AlignmentRecord]`.  Why don't we have the user load the RDD themselves, and then have a function `RDD[AlignmentRecord] => SequenceDictionary`?  If the use wants to do it on a `.bam` file, she can use `adamBamDictionaryLoad`.

* What is the purpose of `maybeLoadBam`?  Make the user check that the file has the proper extension.  How is it useful to return an `Option`?

* What's the purpose of `FeaturesContext`?  It just adds some loading functions.  Could be moved to `ADAMContext`.  Same with `VariationContext`.

* What's the purpose of `GeneContext`?  Seems simpler to implement it by loading GTF `Feature` objects and then transforming the `RDD[Feature]` to `RDD[Gene]`.  Actually, this is what it does, but the implicit pimp-my-lib architecture just seems more confusing.

* `VariantContext` is named strangely as well.

* It's be great to consolidate some of the `*RDDFunctions` whenever possible, though not as obvious to me yet exactly what/how.

A lot of this automagically calling functions by looking at extensions seems like over-complication, and not really that useful.  How often will it happen that the user doesn't know whether they're loading data from a `.bam` file or an `.adam` file?

Why are there so many `*Context` objects?

Thoughts on cleanup/simplification?

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #553 and #456. First 5 commits remove the public `*Context` APIs, and the last commit removes the private `*Context` APIs. All functionality is consolidated down to `ADAMContext`, or moved into the `*RDDFunctions` classes.

### CODE REVIEW

**Comment by fnothaft** [comment]
Rebased on ToT.

**Comment by massie** [comment]
Manually pushed. Thanks, Frank!

**Comment by fnothaft** [comment]
@massie I don't think this was merged properly... these commits aren't in the [master branch](https://github.com/bigdatagenomics/adam/commits/master). Can you double check this? I'll rebase these commits.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by massie** [comment]
I just manually merged this but correctly this time. Sorry I didn't get it right the first time.

**Comment by fnothaft** [comment]
No problem! Thanks for the quick fix!

**Pull request closed without merging**
