### PR TITLE
Add KEYS with public code signing keys

### PR DESCRIPTION
**Pull request by heuermh**
@fnothaft you may append your code signing key to this file with
```
(gpg --list-sigs <your name or id>
             && gpg --armor --export <your name or id>) >> KEYS
```
as described in the header.

### CODE REVIEW

**Comment by fnothaft** [comment]
Opened https://github.com/heuermh/adam/pull/3 with my key.

**Comment by heuermh** [comment]
Should I now rebase this to remove the Merge pull request commit?

**Comment by fnothaft** [comment]
@heuermh I can merge it manually; no sweat!

**Comment by fnothaft** [comment]
Merged as c8718502abcd8ab6a0a85aca895855eb90d1d887 and https://github.com/bigdatagenomics/adam/commit/181bb8f48fd6f276a98d964a5f3eec86c7ff23ca. Thanks @heuermh!

**Comment by heuermh** [comment]
Woot!

**Pull request closed without merging**
