### PR TITLE
[ADAM-867] add pull requests missing from 0.18.0 release to CHANGES.md

### LINKED ISSUE #867: CHANGES.md for 0.18.0 release is missing some fixed issues

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #867

### CODE REVIEW

**Comment by fnothaft** [comment]
`scripts/changelog.sh` overwrites the `CHANGES.md` file each time. Are you sure you want to edit this manually?

**Comment by heuermh** [comment]
No, I don't want to.  :)

I was planning to comment out the changelog script call before running the release script for 0.18.1 and editing ```CHANGES.md``` manually for the 0.18.1 release, with the idea that the changelog script might be fixed between 0.18.1 and 0.19.0.

Our changelog is kind of strange, in that it says ISSUE [#] but then links to the pull request and then displays the description of the pull request, which may contain the issue number ```[ADAM-#]```, which could be but is not a link.

Perhaps for future versions, the changelog might be in the style of

#### Fixed issues
[[ADAM-#]](http://link-to-issue) Issue description

#### Merged pull requests
[#](http://link-to-pull-request) [[ADAM-#]](http://link-to-issue) Pull request description
[#](http://link-to-pull-request) Non-issue merged pull request description

**Comment by fnothaft** [comment]
Merged as https://github.com/bigdatagenomics/adam/commit/a442ec3c3f97ec6ddb7a311b9992835c436e44b2.

**Comment by heuermh** [comment]
Thanks!

**Pull request closed without merging**
