### PR TITLE
[ADAM-513] Remove ReferenceMappable trait.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves (?) #513. Removes the `ReferenceMappable` trait, along with the `ReferenceMappingContext`. Also strips out the visualization code; @erictu will be moving this into a downstream repository.

### CODE REVIEW

**Comment by fnothaft** [comment]
Rebased.

**Comment by laserson** [comment]
Great work, @fnothaft!  I'm happy to merge unless anyone has objections.

**Comment by erictu** [comment]
@fnothaft, did you remember to strip out the webapp folder in adam-cli/src/main/webapp?

**Comment by tdanford** [comment]
I like it too, although I'd (minor quibble) suggest that we could at least drop the VizReads and TrackedLayout stuff as a separate commit (if not a completely separate PR)?

**Comment by fnothaft** [comment]
@erictu ah, forgot that! Will fix.

@tdanford I'll split that into a separate commit.

**Comment by fnothaft** [comment]
Rebased following the #606 merge.

**Comment by laserson** [comment]
Thanks, @fnothaft!  Happy to see `ReferenceMappingContext` go :)

**Pull request merged**
