### PR TITLE
[ADAM-1039] Add basic support for Sample record.

### LINKED ISSUE #1039: VCF sample metadata - proposal for a GenotypedSampleMetadata object
proposal for a GenotypedSampleMetadata avro schema separate from RecordGroup so as to not confound the concept of Read/Record group metadata and VCF sample metadata.

As discussed in https://github.com/bigdatagenomics/adam/pull/1015

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1039.

Arguably, a bit of work to do.

### CODE REVIEW

**Comment by heuermh** [comment]
LGTM

@jpdna the join here is on `Sample.sampleId` ([source](https://github.com/bigdatagenomics/bdg-formats/blob/master/src/main/resources/avro/bdg.avdl#L1195)), can you confirm that is what you were after originally?

**Comment by fnothaft** [comment]
Rebased!

**Comment by jpdna** [comment]
> @jpdna the join here is on Sample.sampleId (source), can you confirm that is what you were after originally?

Yes - LGTM

**Comment by heuermh** [comment]
Merged commit 4b6e107c442a55e3229b45a3990473224f856228.

Thank you, @fnothaft!

**Pull request closed without merging**
