### PR TITLE
Use a lock file to allow only one jenkins test script at a time

### PR DESCRIPTION
**Pull request by massie**

### CODE REVIEW

**Comment by massie** [comment]
Looking at this I realized that Spark 1.1.0 is hard-coded into out jenkins test script. We'll need to address that for Spark 1.2.0 support. We are also downloading Spark each time we run the script; we should probably cache the tarball locally instead.

**Comment by massie** [comment]
Bother. `lockfile` isn't available on the workers. I'll look into this tomorrow with Shane.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Ping @massie @shaneknapp to install `lockfile` on Jenkins.

**Comment by shaneknapp** [comment]
python, i assue...  right?

**Comment by fnothaft** [comment]
Nah, tis a command: [man lockfile](http://linux.die.net/man/1/lockfile)

**Comment by massie** [comment]
I'm starting to question this approach now. A better fix might be to configure Jenkins to guarantee one build per worker. I'll chat with Shane about this more later. I'm going to close this for now.

**Pull request closed without merging**
