### PR TITLE
[ADAM-750] Exclude more sources of Jackson dependency conflicts

### LINKED ISSUE #750: Exclude more Jackson dependency errors
Same as #743, when I try to compile against Spark 1.4.

### PR DESCRIPTION
**Pull request by laserson**
Fixes #750.

### CODE REVIEW

**Comment by fnothaft** [comment]
Does this depend on Spark 1.4?

**Comment by laserson** [comment]
Yes it does.  Ok, just leave this for now and I'll reference it from #752

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Closing in favor of #753.

**Pull request closed without merging**
