### PR TITLE
Why Adam? section added to README.md

### PR DESCRIPTION
**Pull request by tverbeiren**
This PR addresses #497

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by heuermh** [comment]
When I touch this file in a fix for #1307, I'll make the list of formats comprehensive, add mention of Jupyter, and add links for the workbook technologies.  This looks good for now.  Thank you, @tverbeiren!

**Comment by heuermh** [comment]
Thank you, @tverbeiren!

**Comment by fnothaft** [comment]
+1, thank you @tverbeiren and Joke!

**Pull request merged**
