### PR TITLE
Issue#1745 left outer group by left

### LINKED ISSUE #1745: New Shuffle Join Implementation - Left Outer + Group By Left
This is needed to correctly implement a subtract primitive. Without a group by the subtraction returns incorrect intervals.

@fnothaft, @heuermh thoughts on return type? It can be:
`GenericGenomicRDD[(T, Iterable[Option[X]]` 
or
`GenericGenomicRDD[(T, Iterable[X]]` (flattened, so some empty `Iterable`s).

I have no strong preference.

### PR DESCRIPTION
**Pull request by devin-petersohn**
Resolves #1745. Depends on #1741 .

### CODE REVIEW

**Comment by heuermh** [comment]
I squashed and merged #1741, which hopefully was the right thing to do.  You'll need to rebase and squash here.

**Comment by devin-petersohn** [comment]
Resolved docs issues and rebased.

**Comment by fnothaft** [comment]
LGTM, @heuermh please review and merge if OK on your end.

**Comment by heuermh** [comment]
Thank you, @devin-petersohn!

**Pull request merged**
