### PR TITLE
[ADAM-386] Multiline FASTQ input

### PR DESCRIPTION
**Pull request by cket**
[ADAM-386] Adds support for multiline FASTQ input

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, add to whitelist and test this please.

**Comment by cket** [comment]
Thanks for all the help! Everything went smoothly, except not all the commits could be squashed. These two were left, but its a little less messy than the last request. Hopefully this all works this time!

**Comment by fnothaft** [comment]
@cket no problem! I can merge manually and clean those up.

**Comment by fnothaft** [comment]
Merged manually in https://github.com/bigdatagenomics/adam/commit/936bb8a2e1fd911074d1d1c15a85bd039f7f2bcd.

**Pull request closed without merging**
