### PR TITLE
exclude javadoc jar in adam-shell

### PR DESCRIPTION
**Pull request by ryan-williams**
follow-on to 4955aee8ff759f8e619c18a3f5c2352e9265da28

### CODE REVIEW

**Comment by fnothaft** [comment]
LGTM

**Comment by fnothaft** [comment]
@heuermh can you review this real quick?

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
Thanks @ryan-williams! Merged as https://github.com/bigdatagenomics/adam/commit/fb8237e8376e68b631996e7719b441056744c3ea and https://github.com/bigdatagenomics/adam/commit/8da07235077809e0195237789cc51459e09da6f8.

**Pull request closed without merging**
