### PR TITLE
[ADAM-1576] Allow translation between two different GenomicRDD types.

### LINKED ISSUE #1576: Unable to save GenomicRDDs after a join.
There are two things at work here:
1.) We are upcasting to `GenomicRDD` after a join, which does not have any save functionality attached.
2.) `GenericGenomicRDD` extends `GenomicRDD`, but does not have any save functionality attached.

I think it would be ok to create a `GenomicRDD` that is specific to the result joins and other set operations, mimicking the [`PairRDDFunctions`](https://spark.apache.org/docs/2.1.1/api/java/org/apache/spark/rdd/PairRDDFunctions.html) in Spark. I don't see it as a problem for the user to be exposed to a `GenomicPairRDD` or something like that.

What type should a join return? How should we handle subsequent joins on a joined `GenomicRDD`?

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1576. Adds `transmute` function, which is analogous to `transform`, but which allows any return type. This uses an implicit function a la `pipe` to build the output GenomicRDD.

Can I get a quick review pass on this? If this general direction looks good, I will flesh out the implicits for all the allowable transformations.

- [x] Extend to all primary types
- [x] Add docs

### CODE REVIEW

**Comment by fnothaft** [comment]
OK great! I'll flesh this out today. Don't merge as is!

**Comment by fnothaft** [comment]
This is good to go from my end.

**Comment by fnothaft** [comment]
Rebased and cleared conflicts.

**Comment by fnothaft** [comment]
Rebased and cleared conflicts.

**Comment by fnothaft** [comment]
Also, WRT @heuermh's comment, there's nothing that stops an enterprising user from breaking our preconditions today. This might make it easier, but not really any easier than just using `transform` today is.

**Comment by fnothaft** [comment]
Looks like a transient s3 failure.

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
