### PR TITLE
Bump Spark to 1.4

### PR DESCRIPTION
**Pull request by laserson**

### CODE REVIEW

**Comment by laserson** [comment]
This is mainly here to trigger the Jenkins job.

**Comment by massie** [comment]
Update ADAM and ADAM-prb jobs on Jenkins to drop Hadoop 1 checks.

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Can we roll #751 in to this?

**Comment by massie** [comment]
Not sure it's necessary? Both `jackson-core` and `jackson-annotation` are excluded here too as in #751 .

**Comment by massie** [comment]
What say you @laserson ?

**Comment by fnothaft** [comment]
@massie @laserson maybe let's close #751 in favor of this one, then?

**Comment by laserson** [comment]
Ah, yes, feel free.  It includes the relevant commit.

**Comment by fnothaft** [comment]
Done!

**Comment by massie** [comment]
Thanks, @laserson !

**Comment by laserson** [comment]
hmm, i think this was a premature merge.  we're not yet 1.4 compatible

**Comment by massie** [comment]
I reverted the commits. Sorry for the hitting the merge button too soon.

**Pull request merged**
