### PR TITLE
Refactor saving with -single flag

### PR DESCRIPTION
**Pull request by antonstamov**
Inpired by @ryan-williams  [comment] (https://github.com/bigdatagenomics/adam/pull/689#issuecomment-121289139):
`.coalesce(1)` and renaming of `part-r-00000` to dirname is replaced by saving head partition with header and tail partitions without headers (with using of `PartitionPruningRDD`) to two separate `newApiHadoopFIle`s and merging them to `filePath`  with `FileUtil.copyMerge`.
Was tested on ADAM file with 9050501 records. Saved SAM and BAM has same number of records.

### CODE REVIEW

**Comment by massie** [comment]
Jenkins, test this please.

**Comment by massie** [comment]
Please run `./scripts/format-source` on this PR and push the changes.

**Comment by massie** [comment]
@antonstamov I'd like to get this merged as soon as possible. Can you please do the following?

```
$ cd <adam repo>
$ ./scripts/format-source
$ git add .
$ git commit -m "Formatting source"
$ git push --force origin save-as-single-file-refactor:save-as-single-file-refactor
```

This will reformat the source and update this PR. Thank!

**Comment by heuermh** [comment]
FYI I am also interested in seeing this merged, as I would like to add the same feature to #816

**Comment by antonstamov** [comment]
@massie fixed

**Comment by massie** [comment]
This looks good. Can you think of a simple way to add a test? We have a number of small SAM files checked in (see the src/resources/test directories) that you can use as input. For example, create a temp directory, transform a SAM using the `-single` flag and confirm the data is the same.

**Comment by heuermh** [comment]
Thank you @antonstamov!  This has been superceded by #901.

**Pull request closed without merging**
