### PR TITLE
Update to AlignmentRecordField and its usages as contig changed to co…

### PR DESCRIPTION
**Pull request by jpdna**
…ntigName in alignmentRecord

Address #991 raised by @erictu 

updates AlignmentRecordField contig and mateContig to contigName and mateContigName as required by recent  commit 7823abdb0

### CODE REVIEW

**Comment by heuermh** [comment]
+1

**Comment by fnothaft** [comment]
LGTM!

**Comment by fnothaft** [comment]
Merged! Thanks @jpdna!

**Comment by erictu** [comment]
Just tested it downstream, works fine!

**Pull request merged**
