### PR TITLE
Moving API overview from building apps doc to new source file.

### PR DESCRIPTION
**Pull request by heuermh**

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
```
Processing of input or output data failed: Report submission to Coveralls API failed
with HTTP status 500: Internal Server Error (Unexpected character ('<' (code 60)):
expected a valid value (number, String, array, object, 'true', 'false' or 'null')
```
Should we disable Coveralls for the time being?

**Comment by fnothaft** [comment]
Coveralls is So Hot right now @heuermh. Let me take a look at the error message again...

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Pull request merged**
