### PR TITLE
[ADAM-974] Short term fix for multiple ADAM cli assembly jars check

### PR DESCRIPTION
**Pull request by heuermh**
See comment https://github.com/bigdatagenomics/adam/issues/974#issuecomment-201000015.

### CODE REVIEW

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Phew, Mr Jenkins is is a better mood this morning!

**Comment by ryan-williams** [comment]
lgtm, thx @heuermh !

**Comment by heuermh** [comment]
Fixes #974

**Comment by fnothaft** [comment]
Merged as https://github.com/bigdatagenomics/adam/commit/4955aee8ff759f8e619c18a3f5c2352e9265da28. Thanks @heuermh!

**Pull request closed without merging**
