### PR TITLE
removed interval trait and redirected to interval in utils-intervalrdd

### PR DESCRIPTION
**Pull request by akmorrow13**
This is dependent on pull request [#75](https://github.com/bigdatagenomics/utils/pull/75#issuecomment-224050079) in bdg-utils

### CODE REVIEW

**Comment by fnothaft** [comment]
Thanks @akmorrow13! I've just cut the 0.2.7 release of bdg-utils. Once it appears in Maven Central, can you change the pom.xml to point at it?

**Comment by fnothaft** [comment]
0.2.7 is available now: http://search.maven.org/#artifactdetails%7Corg.bdgenomics.utils%7Cutils-parent_2.11%7C0.2.7%7Cpom

**Comment by fnothaft** [comment]
Ping @akmorrow13 to update.

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
Updated thanks @fnothaft !

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by fnothaft** [comment]
Thanks @akmorrow13! Merged.

**Comment by akmorrow13** [comment]
Will a new release be cut soon? We will need this release to use the IntervalRDD.

**Comment by fnothaft** [comment]
We're tracking the release cycle at https://github.com/bigdatagenomics/adam/issues/1048. You can use a snapshot release for now.

**Pull request merged**
