### PR TITLE
[ADAM-1882] Return true if ADAM_HOME is set, not exit 0.

### LINKED ISSUE #1882: adam-submit aborts if ADAM_HOME is set
If `ADAM_HOME` is set, `adam-submit` aborts with the message:
```
java.lang.ClassNotFoundException: org.bdgenomics.adam.cli.ADAMMain
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```

The `bin/find-adam-assembly.sh` used by `adam-submit` sources`bin/find-adam-home`.  `find-adam-home` script exits when `ADAM_HOME` is found. Since it is sourced, the `adam-submit` also exits.

To reproduce this, set `ADAM_HOME` and try running `adam-submit` .

Here's my patch to get it working:
```diff
diff --git a/bin/find-adam-home b/bin/find-adam-home
index 10269078..967f62a1 100755
--- a/bin/find-adam-home
+++ b/bin/find-adam-home
@@ -25,7 +25,7 @@ FIND_ADAM_HOME_PYTHON_SCRIPT="$(cd "$(dirname "$0")"; pwd)/find_adam_home.py"

 # Short cirtuit if the user already has this set.
 if [ ! -z "${ADAM_HOME}" ]; then
-   exit 0
+   true
 elif [ ! -f "$FIND_ADAM_HOME_PYTHON_SCRIPT" ]; then
   # If we are not in the same directory as find_adam_home.py we are not pip installed so we don't
   # need to search the different Python directories for a ADAM installation.
```

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #1882.  Thank you to @pbashyal-nmdp for the patch.

### CODE REVIEW

**Comment by fnothaft** [comment]
@heuermh you should be able to apply the patch as @pbashyal-nmdp.

**Comment by heuermh** [comment]
> @heuermh you should be able to apply the patch as @pbashyal-nmdp.

Teach me?

**Comment by fnothaft** [comment]
See over at #1905. I put the patch in a file named `patch-1882`. Then, I did:

```
git apply patch-1882
git commit -a --author="authorname <author@email.com>"
```

**Comment by heuermh** [comment]
Closed in favor of #1905.

**Pull request closed without merging**
