### PR TITLE
[ADAM-1221] Bump Spark/Hadoop versions.

### LINKED ISSUE #1221: Bump Spark, Scala, Hadoop dependency versions
Apache Spark version 2.0.1 was released on 03 Oct 2016 and defaults to Scala version 2.11.8 and Hadoop 2.7 and later.

Apache Spark version 1.6.2 was released on 25 June 2016 and defaults to Scala version 2.10.5 and Hadoop 2.6.  When bumping the Scala version to 2.10.5 downstream I see other libraries requiring 2.10.6.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #1221.

### CODE REVIEW

**Comment by heuermh** [comment]
Need to update here as well
https://github.com/bigdatagenomics/adam/blob/master/scripts/move_to_spark_2.sh#L13

**Comment by fnothaft** [comment]
Ah, thanks for the catch! I had looked at the scala 2.10/2.11 scripts but not the Spark 2 one.

**Comment by fnothaft** [comment]
Fixed!

**Comment by fnothaft** [comment]
This is good to go.

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
