### PR TITLE
[ADAM-1093] Move to support Spark 2.0.0.

### LINKED ISSUE #1093: ADAM version 0.19.0 will not run on Spark version 2.0.0
We knew this would happen; with Spark version 2.0.0 installed from Homebrew and ADAM version 0.19.0 installed from Homebrew Science
```bash
$ spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.0.0
      /_/
                        
Branch 
Compiled by user jenkins on 2016-07-19T21:16:09Z
Revision 
Url 
Type --help for more information.

$ adam-submit --version
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-submit
java.lang.NoClassDefFoundError: org/apache/spark/Logging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:225)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:686)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.Logging
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

ADAM git HEAD version 0.19.1-SNAPSHOT runs ok
```bash
$ ./bin/adam-submit --version
Using ADAM_MAIN=org.bdgenomics.adam.cli.ADAMMain
Using SPARK_SUBMIT=/usr/local/bin/spark-submit

       e         888~-_          e             e    e
      d8b        888   \        d8b           d8b  d8b
     /Y88b       888    |      /Y88b         d888bdY88b
    /  Y88b      888    |     /  Y88b       / Y88Y Y888b
   /____Y88b     888   /     /____Y88b     /   YY   Y888b
  /      Y88b    888_-~     /      Y88b   /          Y888b

ADAM version: 0.19.1-SNAPSHOT
Commit: c23aace7b1739e29935cd3f46781ae0befc0a756 Build: 2016-07-29
Built for: Scala 2.10 and Hadoop 2.6.0
```

Note the Spark binary tarball used by Homebrew was built against Scala 2.11 and Hadoop 2.7
https://www.apache.org/dyn/closer.lua?path=spark/spark-2.0.0/spark-2.0.0-bin-hadoop2.7.tgz

whereas we still build by default for Hadoop 2.6.0 and use the Scala 2.10 binary tarball for the Homebrew Science formula.

### PR DESCRIPTION
**Pull request by fnothaft**
Relies on https://github.com/bigdatagenomics/utils/pull/78. Resolves #1093:

* Clean up logging in VariantContextRDD
* Add move_to_spark_2.sh script and CI hooks

### CODE REVIEW

**Comment by fnothaft** [comment]
Rebased. Once this passes tests, @heuermh or I can cut a release of bdg-utils, and then I'll update this PR with the non-snapshot coordinates.

**Comment by fnothaft** [comment]
Hooray! I'll cut utils-0.2.8 upstream.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by fnothaft** [comment]
Just realized that Jenkins didn't run the 2.0.0 tests. Updated Jenkins, and kicked those off now!

**Comment by heuermh** [comment]
utils 0.2.8 artifacts are available from Maven Central.

**Comment by heuermh** [comment]
We also need a `move_to_spark_1.sh` script and need to have this called near the end of `release.sh`.

I don't know what the spark packages zip file is, does that also need Spark 1.x and 2.x versions?

**Comment by fnothaft** [comment]
Updated with the final release version for utils.

> We also need a move_to_spark_1.sh script and need to have this called near the end of release.sh.

Actually, we don't! (That's what I like about the release scripts here.) We do all of the releases from maintenance branches, and only update the versions on the master branch, so the POMs on the master branch don't get touched.

**Comment by heuermh** [comment]
> the POMs on the master branch don't get touched

Ah, ok.  LGTM then.

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
