### PR TITLE
Set defaults to schemas

### PR DESCRIPTION
**Pull request by ffinfo**
For user convenience when working with scala

### CODE REVIEW

**Comment by ffinfo** [comment]
Also changed to case classes, better native scala/dataset support

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by heuermh** [comment]
Looks reasonable to me, thank you, @ffinfo!

**Comment by heuermh** [comment]
@fnothaft milestone 0.24.1?

**Comment by heuermh** [comment]
Thank you, @ffinfo!  Squashed and merged as commit afa55a4

**Pull request merged**
