### PR TITLE
[ADAM-743] exclude conflicting jackson dependencies

### LINKED ISSUE #743: adam-cli unit test NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
adam-cli unit tests generate large numbers of stack traces related to conflicts in jackson transitive dependency versions
```bash
$ mvn install
...
Adam2FastqSuite:
2015-07-27 13:02:59 ERROR MetricsSystem:96 - Sink class org.apache.spark.metrics.sink.MetricsServlet cannot be instantialized
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor51.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:173)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:167)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:98)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:226)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:39)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:98)
	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:167)
	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:89)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:346)
	at org.bdgenomics.utils.misc.SparkFunSuite$class.setupSparkContext(SparkFunSuite.scala:51)
	at org.bdgenomics.adam.cli.Adam2FastqSuite.setupSparkContext(ADAM2FastqSuite.scala:27)
	at org.bdgenomics.utils.misc.SparkFunSuite$$anonfun$sparkTest$1.apply$mcV$sp(SparkFunSuite.scala:94)
	at org.bdgenomics.utils.misc.SparkFunSuite$$anonfun$sparkTest$1.apply(SparkFunSuite.scala:93)
	at org.bdgenomics.utils.misc.SparkFunSuite$$anonfun$sparkTest$1.apply(SparkFunSuite.scala:93)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.bdgenomics.adam.cli.Adam2FastqSuite.org$scalatest$BeforeAndAfter$$super$runTest(ADAM2FastqSuite.scala:27)
	at org.scalatest.BeforeAndAfter$class.runTest(BeforeAndAfter.scala:200)
	at org.bdgenomics.adam.cli.Adam2FastqSuite.runTest(ADAM2FastqSuite.scala:27)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at org.bdgenomics.adam.cli.Adam2FastqSuite.org$scalatest$BeforeAndAfter$$super$run(ADAM2FastqSuite.scala:27)
	at org.scalatest.BeforeAndAfter$class.run(BeforeAndAfter.scala:241)
	at org.bdgenomics.adam.cli.Adam2FastqSuite.run(ADAM2FastqSuite.scala:27)
	at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1492)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1528)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1526)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1526)
	at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
	at org.scalatest.Suite$class.run(Suite.scala:1421)
	at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.main(Runner.scala:860)
	at org.scalatest.tools.Runner.main(Runner.scala)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonFactory.requiresPropertyOrdering()Z
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:445)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:366)
	at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:45)
	... 73 more
```

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #743

### CODE REVIEW

**Comment by fnothaft** [comment]
What are the conflicting jackson dependencies used for in utils?
Nit: can you prefix the commit message with `[ADAM-774]`?

**Comment by heuermh** [comment]
HEAD contains versions 2.1.x and 2.3.x
```bash
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ADAM_2.10: CLI 0.17.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ adam-cli_2.10 ---
[INFO] org.bdgenomics.adam:adam-cli_2.10:jar:0.17.1-SNAPSHOT
...
[INFO] +- org.apache.spark:spark-core_2.10:jar:1.2.0:provided
...
[INFO] |  +- org.json4s:json4s-jackson_2.10:jar:3.2.10:provided
[INFO] |  |  +- org.json4s:json4s-core_2.10:jar:3.2.10:provided
[INFO] |  |  |  +- org.json4s:json4s-ast_2.10:jar:3.2.10:provided
[INFO] |  |  |  \- org.scala-lang:scalap:jar:2.10.0:provided
[INFO] |  |  |     \- org.scala-lang:scala-compiler:jar:2.10.0:provided
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.3.1:provided
...
[INFO] +- org.bdgenomics.utils:utils-io_2.10:jar:0.2.2:compile
[INFO] |  +- org.bdgenomics.utils:utils-misc_2.10:jar:0.2.2:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.3.1:compile
[INFO] |  \- com.amazonaws:aws-java-sdk:jar:1.7.5:provided
[INFO] |     +- com.fasterxml.jackson.core:jackson-core:jar:2.1.1:provided
[INFO] |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.1.1:provided
...
```

vs. 2.3.x for this pull request
```bash
$ mvn dependency:tree
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building ADAM_2.10: CLI 0.17.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ adam-cli_2.10 ---
[INFO] org.bdgenomics.adam:adam-cli_2.10:jar:0.17.1-SNAPSHOT
...
[INFO] +- org.apache.spark:spark-core_2.10:jar:1.2.0:provided
...
[INFO] |  +- org.json4s:json4s-jackson_2.10:jar:3.2.10:provided
[INFO] |  |  +- org.json4s:json4s-core_2.10:jar:3.2.10:provided
[INFO] |  |  |  +- org.json4s:json4s-ast_2.10:jar:3.2.10:provided
[INFO] |  |  |  \- org.scala-lang:scalap:jar:2.10.0:provided
[INFO] |  |  |     \- org.scala-lang:scala-compiler:jar:2.10.0:provided
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.3.1:provided
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.3.0:provided
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.3.1:provided
[INFO] +- org.bdgenomics.utils:utils-io_2.10:jar:0.2.2:compile
[INFO] |  +- org.bdgenomics.utils:utils-misc_2.10:jar:0.2.2:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.3.2:compile
[INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.3.1:compile
[INFO] |  \- com.amazonaws:aws-java-sdk:jar:1.7.5:provided
...
```

**Comment by fnothaft** [comment]
Ah. I was more going for, what code in utils has the jackson dependency? I think we may be able to fix that in utils by removing or upgrading the Jackson dep; it may be old?

**Comment by heuermh** [comment]
From what I can see there isn't a direct dependency.  It appears to be a transitive dependency where old versions are pulled in by ```aws-java-sdk``` in the module ```utils-io```.

The class in the stack trace is part of Apache Spark
https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/metrics/sink/MetricsServlet.scala

**Comment by fnothaft** [comment]
Ah, OK! SGTM.

**Comment by fnothaft** [comment]
Merged! Thanks @heuermh!

**Pull request merged**
